// ---------------------------------------------------------------------------
// MCP App Bridge — Iframe Creation Utilities
//
// Creates sandboxed iframes for MCP Apps with CSP injection per SS10.3.
// Theme CSS variables (ext-apps spec tokens + NB extension tokens) are
// injected alongside CSP so they are available at parse time in every iframe.
// ---------------------------------------------------------------------------

import type { ThemeMode } from "./theme.ts";
import { buildThemeStyleBlock, getHostThemeMode } from "./theme.ts";

/** Options for iframe creation. */
export interface CreateIframeOptions {
  /** Allowed external connect-src domains from the bundle manifest. */
  connectDomains?: string[];
  /** Theme mode override. Defaults to the host page's current mode. */
  themeMode?: ThemeMode;
}

/**
 * Build the CSP policy string per SS10.3.
 *
 * - default-src 'none'
 * - script-src 'self' 'unsafe-inline'
 * - style-src 'self' 'unsafe-inline'
 * - img-src 'self' data: blob:
 * - font-src 'self' data:
 * - connect-src {allowed_domains} or 'none'
 * - frame-src 'self' (allows same-origin resources like PDF previews)
 * - object-src 'none'
 * - base-uri 'none'
 */
export function buildCSP(connectDomains?: string[]): string {
  const connectSrc =
    connectDomains && connectDomains.length > 0 ? connectDomains.join(" ") : "'none'";

  // Allow blob: URLs for inline content rendering (e.g., PDF preview from tool data).
  const frameSrc = "blob:";

  return [
    "default-src 'none'",
    "script-src 'self' 'unsafe-inline'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob: https:",
    "font-src 'self' data:",
    `connect-src ${connectSrc}`,
    `frame-src ${frameSrc}`,
    "object-src 'none'",
    "base-uri 'none'",
  ].join("; ");
}

/**
 * Inject a `<style>` block with NimbleBrain theme CSS variables into the HTML.
 *
 * Inserts into `<head>` when present, otherwise prepends (same fallback
 * pattern as `injectCSP`). The style block is generated by
 * `buildThemeStyleBlock` so theme variables are available at parse time.
 */
export function injectThemeStyles(html: string, mode: ThemeMode): string {
  const styleTag = buildThemeStyleBlock(mode);

  // Insert after <head> tag
  const headPattern = /<head(\s[^>]*)?>|<head>/i;
  if (headPattern.test(html)) {
    return html.replace(headPattern, (match) => `${match}\n${styleTag}`);
  }

  // No <head> tag — prepend (best effort for fragments)
  return `${styleTag}\n${html}`;
}

/**
 * Inject or replace a CSP meta tag in the HTML document's <head>.
 *
 * If a CSP meta tag already exists, it is replaced. Otherwise, one is
 * inserted as the first child of <head>.
 */
export function injectCSP(html: string, policy: string): string {
  const metaTag = `<meta http-equiv="Content-Security-Policy" content="${policy}">`;

  // Try to replace an existing CSP meta tag
  const cspPattern = /<meta\s+http-equiv=["']Content-Security-Policy["'][^>]*>/i;
  if (cspPattern.test(html)) {
    return html.replace(cspPattern, metaTag);
  }

  // Insert after <head> tag
  const headPattern = /<head(\s[^>]*)?>|<head>/i;
  if (headPattern.test(html)) {
    return html.replace(headPattern, (match) => `${match}\n${metaTag}`);
  }

  // No <head> tag — prepend the meta tag (best effort for fragments)
  return `${metaTag}\n${html}`;
}

/**
 * Create a sandboxed iframe for an MCP App.
 *
 * Sandbox attributes per SS10.3:
 * - allow-scripts: JavaScript execution
 * - allow-same-origin: Needed for postMessage origin checks
 * - allow-popups: External link opening
 * - allow-popups-to-escape-sandbox: Opened popups are not sandboxed
 *
 * Explicitly NOT allowed: allow-forms, allow-top-navigation, allow-modals.
 */
export function createAppIframe(
  html: string,
  appName: string,
  options?: CreateIframeOptions,
): HTMLIFrameElement {
  const iframe = document.createElement("iframe");

  // Sandbox attributes per SS10.3
  iframe.sandbox.add(
    "allow-scripts",
    "allow-same-origin",
    "allow-popups",
    "allow-popups-to-escape-sandbox",
  );

  // Permissions Policy: allow clipboard write (copy/cut) inside the iframe.
  // clipboard-read is intentionally omitted — it would let apps read the
  // clipboard programmatically without user gesture, which is a data
  // exfiltration risk for untrusted MCP apps.
  iframe.allow = "clipboard-write";

  // Inject theme CSS variables into the HTML
  const themeMode = options?.themeMode ?? getHostThemeMode();
  const themedHtml = injectThemeStyles(html, themeMode);

  // Inject CSP into the HTML
  const csp = buildCSP(options?.connectDomains);
  const securedHtml = injectCSP(themedHtml, csp);

  // Use srcdoc (not src URL) per spec
  iframe.srcdoc = securedHtml;

  // Track app name for event routing
  iframe.dataset.app = appName;

  // Remove default iframe border
  iframe.style.border = "none";

  return iframe;
}
