// ---------------------------------------------------------------------------
// Runtime validation for App → Host postMessage envelopes.
//
// The iframe is a trust boundary — Synapse apps from third-party bundles
// and Reboot prototypes execute inside it. Anything coming OUT of the
// iframe must be shape-checked before the host acts on it. Anything going
// IN is generated by code we own and is type-checked at compile time;
// runtime validation there is defensive against ourselves and not worth
// the bundle weight.
//
// Strategy: discriminator-aware validation. If the inbound message's
// `method` matches one we declared a schema for, validate strictly
// against that specific schema. If it doesn't, return `ok: true` and
// let the existing `switch (msg.method)` handler in bridge.ts handle it
// (typically by ignoring it). This adds shape enforcement on every
// message the host actually acts on, without changing the semantics
// for unknown methods.
//
// We use TypeBox's `Value.Check` rather than AJV: ~3kb min+gzip, no
// separate validator dep, no compilation step. postMessage frequency
// is not a hot path so the per-call cost is irrelevant.
// ---------------------------------------------------------------------------

import type { TSchema } from "@sinclair/typebox";
import { Value } from "@sinclair/typebox/value";
import {
  ExtAppsInitializedNotification,
  ExtAppsInitializeRequest,
  ExtAppsRequestTeardownNotification,
  ResourcesReadMessage,
  SynapseRequestFileMessage,
  ToolsCallMessage,
  UiActionMessage,
  UiDownloadFileMessage,
  UiKeydownMessage,
  UiMessageMessage,
  UiOpenLinkMessage,
  UiPersistStateMessage,
  UiSizeChangedMessage,
  UiUpdateModelContextMessage,
} from "./schemas";

/** Map from `method` literal → schema for that envelope. */
const SCHEMA_BY_METHOD: Record<string, TSchema> = {
  "tools/call": ToolsCallMessage,
  "resources/read": ResourcesReadMessage,
  "ui/message": UiMessageMessage,
  "ui/open-link": UiOpenLinkMessage,
  "ui/notifications/size-changed": UiSizeChangedMessage,
  "ui/update-model-context": UiUpdateModelContextMessage,
  "ui/initialize": ExtAppsInitializeRequest,
  "ui/notifications/initialized": ExtAppsInitializedNotification,
  "ui/notifications/request-teardown": ExtAppsRequestTeardownNotification,
  "synapse/action": UiActionMessage,
  "synapse/download-file": UiDownloadFileMessage,
  "synapse/persist-state": UiPersistStateMessage,
  "synapse/request-file": SynapseRequestFileMessage,
  "synapse/keydown": UiKeydownMessage,
};

export interface AppToHostValidationResult {
  /** True iff the message is either unrecognized (let downstream handle it) or
   *  matches its declared schema. False means "drop this message". */
  ok: boolean;
  /** Method name extracted from the envelope, when present. */
  method: string | null;
  /** Human-readable summary of the first failure, or null on success. */
  reason: string | null;
}

/**
 * Validate that an inbound postMessage payload conforms to the schema
 * declared for its `method`. Messages with no `method` or an unrecognized
 * one return `{ ok: true, method }` — the caller's existing switch will
 * either handle them or ignore them, same as before this validator existed.
 *
 * Callers should treat `ok: false` as "drop this message and log the
 * reason" — a malformed envelope is either a buggy app or a probe.
 */
export function validateAppToHostMessage(value: unknown): AppToHostValidationResult {
  if (!value || typeof value !== "object") {
    return { ok: false, method: null, reason: "Message is not an object" };
  }
  const method =
    "method" in value && typeof (value as { method: unknown }).method === "string"
      ? ((value as { method: string }).method as string)
      : null;
  if (!method) {
    // No method → either a JSON-RPC response (id + result/error) or junk.
    // Responses don't pass through this code path (the bridge correlates
    // them via id elsewhere). Returning ok lets the existing handler
    // fall through to its no-method early return.
    return { ok: true, method: null, reason: null };
  }
  const schema = SCHEMA_BY_METHOD[method];
  if (!schema) {
    // Unknown method — let the existing switch handler decide. Most fall
    // through to the default (no-op) branch.
    return { ok: true, method, reason: null };
  }
  if (Value.Check(schema, value)) {
    return { ok: true, method, reason: null };
  }
  const errors = [...Value.Errors(schema, value)];
  if (errors.length === 0) {
    return { ok: false, method, reason: "Unknown validation failure" };
  }
  const first = errors[0];
  return { ok: false, method, reason: `${first.path || "(root)"}: ${first.message}` };
}
