import { resolve } from "node:path";
import type { LanguageModelV3Content, LanguageModelV3Message } from "@ai-sdk/provider";

/**
 * Conversation IDs are `conv_` followed by exactly 16 lowercase hex characters.
 * Generated by: `conv_${crypto.randomUUID().replace(/-/g, "").slice(0, 16)}`
 */
export const CONVERSATION_ID_RE = /^conv_[a-f0-9]{16}$/;

/**
 * Validate a conversation ID and resolve its file path safely.
 * Throws if the ID format is invalid or the resolved path escapes the base directory.
 */
export function validateConversationId(id: string, dir: string): void {
  if (!CONVERSATION_ID_RE.test(id)) {
    throw new Error(`Invalid conversation ID: must match conv_ + 16 hex chars`);
  }
  const resolved = resolve(dir, `${id}.jsonl`);
  if (!resolved.startsWith(resolve(dir))) {
    throw new Error("Path traversal detected");
  }
}

/** Access context for filtering conversations by user identity and role. */
export interface ConversationAccessContext {
  userId: string;
  workspaceRole?: "admin" | "member";
}

/** Options for listing conversations. */
export interface ListOptions {
  limit?: number;
  cursor?: string;
  search?: string;
  sortBy?: "createdAt" | "updatedAt";
}

/** Paginated conversation list result. */
export interface ConversationListResult {
  conversations: ConversationSummary[];
  nextCursor: string | null;
  totalCount: number;
}

/** Options for creating a new conversation. */
export interface CreateConversationOptions {
  workspaceId?: string;
  ownerId?: string;
  visibility?: "private" | "shared";
  participants?: string[];
  metadata?: Record<string, unknown>;
}

/** Fields that can be updated on a conversation. */
export interface ConversationPatch {
  title?: string;
}

export interface ConversationSummary {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string | null;
  messageCount: number;
  preview: string;
  totalInputTokens: number;
  totalOutputTokens: number;
  totalCostUsd: number;
  ownerId?: string;
  visibility?: "private" | "shared";
  workspaceId?: string;
  participants?: string[];
}

export interface ConversationStore {
  create(options?: CreateConversationOptions): Promise<Conversation>;
  load(id: string, access?: ConversationAccessContext): Promise<Conversation | null>;
  append(conversation: Conversation, message: StoredMessage): Promise<void>;
  history(conversation: Conversation, limit?: number): Promise<StoredMessage[]>;
  list(options?: ListOptions, access?: ConversationAccessContext): Promise<ConversationListResult>;
  /** Delete a conversation and its backing store. Returns true if found. */
  delete(id: string): Promise<boolean>;
  /** Update conversation metadata. Returns updated conversation or null if not found. */
  update(id: string, patch: ConversationPatch): Promise<Conversation | null>;
  /** Fork a conversation, optionally truncating at a specific message index. */
  fork(id: string, atMessage?: number): Promise<Conversation | null>;
  /** Change visibility from private to shared. Only the owner (or admin) may call this. */
  shareConversation(id: string, ownerId: string): Promise<Conversation | null>;
  /** Change visibility back to private. Removes all participants except the owner. */
  unshareConversation(id: string, ownerId: string): Promise<Conversation | null>;
  /** Add a participant to a shared conversation. */
  addParticipant(id: string, userId: string): Promise<Conversation | null>;
  /** Remove a participant from a shared conversation. Cannot remove the owner. */
  removeParticipant(id: string, userId: string): Promise<Conversation | null>;
}

/** Conversation metadata — stored as line 1 of the JSONL file. */
export interface Conversation {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string | null;
  totalInputTokens: number;
  totalOutputTokens: number;
  totalCostUsd: number;
  lastModel: string | null;
  /** Workspace this conversation belongs to. */
  workspaceId?: string;
  /** User who created this conversation. */
  ownerId?: string;
  /** Visibility: private (default) or shared within workspace. */
  visibility?: "private" | "shared";
  /** User IDs participating in this conversation. */
  participants?: string[];
  /** Arbitrary caller-provided metadata. Stored in JSONL first line, never validated. */
  metadata?: Record<string, unknown>;
  /** File format discriminator. "events" for event-sourced files. Absent for legacy message format. */
  format?: "events";
}

/** Participant info for system prompt injection in shared conversations. */
export interface ParticipantInfo {
  userId: string;
  displayName?: string;
}

export type StoredMessage = LanguageModelV3Message & {
  timestamp: string;
  /** User who sent this message (for multi-user conversations). */
  userId?: string;
  metadata?: {
    skill?: string | null;
    toolCalls?: Array<{
      id: string;
      name: string;
      input: Record<string, unknown>;
      output: string;
      ok: boolean;
      ms: number;
      resourceUri?: string;
      resourceLinks?: Array<{
        uri: string;
        name?: string;
        mimeType?: string;
        description?: string;
      }>;
    }>;
    inputTokens?: number;
    outputTokens?: number;
    cacheReadTokens?: number;
    costUsd?: number;
    model?: string;
    llmMs?: number;
    iterations?: number;
    /** Per-call finish reason — surfaces length truncation etc. to the UI. */
    finishReason?: "stop" | "length" | "content-filter" | "tool-calls" | "error" | "other";
    files?: Array<{
      id: string;
      filename: string;
      mimeType: string;
      size: number;
      extracted: boolean;
    }>;
  };
};

// ---------------------------------------------------------------------------
// Event-sourced conversation events
// ---------------------------------------------------------------------------

export type ConversationEventType =
  | "user.message"
  | "run.start"
  | "llm.response"
  | "tool.start"
  | "tool.done"
  | "tool.progress"
  | "run.done"
  | "run.error"
  | "skills.loaded"
  | "context.assembled"
  | "metadata.title"
  | "metadata.visibility"
  | "metadata.participants";

export interface UserMessageEvent {
  ts: string;
  type: "user.message";
  content: LanguageModelV3Content[];
  userId?: string;
  files?: Array<{
    id: string;
    filename: string;
    mimeType: string;
    size: number;
    extracted: boolean;
  }>;
}

export interface RunStartEvent {
  ts: string;
  type: "run.start";
  runId: string;
  model: string;
  /** Present only when logging.level is "debug". */
  systemPrompt?: string;
  /** Present only when logging.level is "debug". */
  messages?: unknown[];
  /** Present only when logging.level is "debug". */
  toolSchemas?: string[];
}

export interface LlmResponseEvent {
  ts: string;
  type: "llm.response";
  runId: string;
  model: string;
  /**
   * V3 content blocks. Includes `text`, `tool-call`, and `reasoning`
   * (extended thinking) parts. Reasoning blocks are surfaced to the UI
   * collapsed-by-default; bare absence on a turn with non-stop
   * finishReason is what indicates a real empty turn.
   */
  content: LanguageModelV3Content[];
  inputTokens: number;
  outputTokens: number;
  /**
   * Reasoning-token subtotal (subset of `outputTokens`). 0 when the model
   * emitted no reasoning. Useful for cost attribution and for diagnosing
   * "why is outputTokens at the cap with empty visible content?".
   */
  reasoningTokens?: number;
  cacheReadTokens: number;
  cacheCreationTokens: number;
  llmMs: number;
  /**
   * Per-call finish reason from the provider (AI SDK V3 unified value).
   * Optional for backward-compat with conversations recorded before this
   * field existed.
   */
  finishReason?: "stop" | "length" | "content-filter" | "tool-calls" | "error" | "other";
}

export interface ToolStartEvent {
  ts: string;
  type: "tool.start";
  runId: string;
  name: string;
  id: string;
  /** Present only when logging.level is "debug". */
  input?: unknown;
}

export interface ToolDoneEvent {
  ts: string;
  type: "tool.done";
  runId: string;
  name: string;
  id: string;
  ok: boolean;
  ms: number;
  /** Present only when logging.level is "debug". */
  output?: string;
}

export interface ToolProgressEvent {
  ts: string;
  type: "tool.progress";
  runId: string;
  id: string;
  message: string;
}

export interface RunDoneEvent {
  ts: string;
  type: "run.done";
  runId: string;
  stopReason: string;
  totalMs: number;
}

export interface RunErrorEvent {
  ts: string;
  type: "run.error";
  runId: string;
  error: string;
  errorType: string;
}

export interface TitleChangeEvent {
  ts: string;
  type: "metadata.title";
  title: string | null;
}

export interface VisibilityChangeEvent {
  ts: string;
  type: "metadata.visibility";
  visibility: "private" | "shared";
}

export interface ParticipantsChangeEvent {
  ts: string;
  type: "metadata.participants";
  participants: string[];
}

/**
 * Per-skill telemetry attached to a `skills.loaded` event. One entry per
 * Layer 3 skill that the loader selected for this turn.
 *
 * `version` is the file mtime as ISO 8601 (cheap, stable). `tokens` is an
 * approximate count (`Math.ceil(body.length / 4)`); replace with a real
 * tokenizer in Phase 5 once attribution lands.
 */
export interface SkillsLoadedEntry {
  id: string;
  layer: 3;
  scope: "platform" | "workspace" | "user" | "bundle";
  version: string;
  tokens: number;
  loadedBy: "always" | "tool_affinity";
  reason: string;
}

export interface SkillsLoadedEvent {
  ts: string;
  type: "skills.loaded";
  runId: string;
  skills: SkillsLoadedEntry[];
  totalTokens: number;
}

/**
 * Snapshot of context assembled for a turn — counts and tokens only, no
 * content (the bodies are already in the conversation log via earlier
 * source events / message history).
 *
 * Each `sources[]` entry is a `{kind, ...}` row. `kind` values include
 * `"system_prompt"`, `"tool_descriptions"`, `"history"`, and the per-source
 * kinds Phase 2 introduces (`"skills"`). Future phases add more kinds; the
 * shape is open for extension.
 */
export interface ContextAssembledSource {
  kind: string;
  count?: number;
  tokens: number;
  /** Optional discriminators per source kind. */
  toolSetHash?: string;
  version?: string | number;
  userId?: string;
  turns?: number;
  compacted?: boolean;
}

export interface ContextAssembledEvent {
  ts: string;
  type: "context.assembled";
  runId: string;
  sources: ContextAssembledSource[];
  excluded: ContextAssembledSource[];
  totalTokens: number;
  modelMaxContext?: number;
  headroomTokens?: number;
}

/** Discriminated union of all conversation event types. */
export type ConversationEvent =
  | UserMessageEvent
  | RunStartEvent
  | LlmResponseEvent
  | ToolStartEvent
  | ToolDoneEvent
  | ToolProgressEvent
  | RunDoneEvent
  | RunErrorEvent
  | SkillsLoadedEvent
  | ContextAssembledEvent
  | TitleChangeEvent
  | VisibilityChangeEvent
  | ParticipantsChangeEvent;
