import { resolve } from "node:path";
import type {
  LanguageModelV3Content,
  LanguageModelV3Message,
  LanguageModelV3TextPart,
  SharedV3ProviderOptions,
} from "@ai-sdk/provider";
import type { ResourceLinkInfo } from "../engine/content-helpers.ts";
import type { ContextAssembledSource, SkillsLoadedEntry } from "../engine/types.ts";
import type { TokenUsage } from "../usage/types.ts";

// Re-export so conversation-event consumers don't need to know these
// originate in engine/types.ts. Engine emits them; conversation persists
// them; one definition keeps the wire shape from drifting.
export type { ContextAssembledSource, SkillsLoadedEntry };

/**
 * Conversation IDs are `conv_` followed by exactly 16 lowercase hex characters.
 * Generated by: `conv_${crypto.randomUUID().replace(/-/g, "").slice(0, 16)}`
 */
export const CONVERSATION_ID_RE = /^conv_[a-f0-9]{16}$/;

/**
 * Validate a conversation ID and resolve its file path safely.
 * Throws if the ID format is invalid or the resolved path escapes the base directory.
 */
export function validateConversationId(id: string, dir: string): void {
  if (!CONVERSATION_ID_RE.test(id)) {
    throw new Error(`Invalid conversation ID: must match conv_ + 16 hex chars`);
  }
  const resolved = resolve(dir, `${id}.jsonl`);
  if (!resolved.startsWith(resolve(dir))) {
    throw new Error("Path traversal detected");
  }
}

/**
 * Access context for filtering conversations by user identity.
 *
 * Stage 1: single-owner only. A conversation is accessible iff the
 * caller's `userId` matches the conversation's `ownerId`.
 *
 * Stage 4 reintroduces sharing primitives with policy gating and will
 * extend this context (workspace-admin override, sharing claims, etc.).
 * Defining them now would be a no-op slot — the type tracks what
 * Stage 1 actually uses.
 */
export interface ConversationAccessContext {
  userId: string;
}

/** Options for listing conversations. */
export interface ListOptions {
  limit?: number;
  cursor?: string;
  search?: string;
  sortBy?: "createdAt" | "updatedAt";
  /**
   * Restrict the listing to one room. The room-scoped conversation view (a
   * single `workspaces/<wsId>/conversations/` subtree); omit for the owner's
   * "All rooms" view across every workspace they belong to. Orthogonal to
   * `access` — `workspaceId` is the path filter, ownership is the access gate.
   */
  workspaceId?: string;
}

/** Paginated conversation list result. */
export interface ConversationListResult {
  conversations: ConversationSummary[];
  nextCursor: string | null;
  totalCount: number;
}

/**
 * Options for creating a new conversation.
 *
 * `ownerId` is required — the conversation is owned by exactly one user.
 * `workspaceId` is the room the chat is born in (the binding moment is the
 * first message); it determines the storage directory and is fixed for the
 * conversation's life — there is no mid-chat room switching. When `automationId`
 * is set the conversation is an automation run and lands in that room's
 * `_runs/<automationId>/` partition instead of the owner partition.
 */
export interface CreateConversationOptions {
  workspaceId?: string;
  ownerId: string;
  /** When set, this is an automation run — stored under `_runs/<automationId>/`. */
  automationId?: string;
  metadata?: Record<string, unknown>;
  /** Create with a specific id instead of a generated one. Used by the
   *  detached-turn path so the conversation id is known to the caller before
   *  the engine run starts. */
  id?: string;
}

/** Fields that can be updated on a conversation. */
export interface ConversationPatch {
  title?: string;
}

export interface ConversationSummary {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string | null;
  messageCount: number;
  preview: string;
  totalInputTokens: number;
  totalOutputTokens: number;
  totalCostUsd: number;
  /**
   * Owner of the conversation. Required: Stage 1 invariant says every
   * conversation has an owner. Files lacking `ownerId` are excluded
   * from the index entirely (see `parseFileHeader`), and direct
   * `load()` calls on such files throw.
   */
  ownerId: string;
  workspaceId?: string;
}

export interface ConversationStore {
  create(options: CreateConversationOptions): Promise<Conversation>;
  load(id: string, access?: ConversationAccessContext): Promise<Conversation | null>;
  append(conversation: Conversation, message: StoredMessage): Promise<void>;
  history(conversation: Conversation, limit?: number): Promise<StoredMessage[]>;
  /**
   * Append a raw conversation event to the stream. Event-sourced stores only —
   * absent on message-based stores (legacy JSONL, in-memory), so callers must
   * feature-detect. Used for events the engine-event sink doesn't produce, e.g.
   * `history.compacted` written by the compaction path.
   */
  appendEvent?(id: string, event: ConversationEvent): void;
  list(options?: ListOptions, access?: ConversationAccessContext): Promise<ConversationListResult>;
  /**
   * Delete a conversation and its backing store. Returns true if the
   * conversation existed AND the caller is allowed to delete it. When
   * `access` is supplied, a non-owner gets `false` (same shape as "not
   * found") — the caller can't distinguish existence-but-not-yours from
   * doesn't-exist, which is the right posture at the store layer.
   */
  delete(id: string, access?: ConversationAccessContext): Promise<boolean>;
  /**
   * Update conversation metadata. Returns the updated conversation, or
   * `null` if the conversation doesn't exist OR — when `access` is
   * supplied — the caller isn't the owner.
   */
  update(
    id: string,
    patch: ConversationPatch,
    access?: ConversationAccessContext,
  ): Promise<Conversation | null>;
  /**
   * Fork a conversation, optionally truncating at a specific message
   * index. Returns the new conversation, or `null` if the source doesn't
   * exist OR — when `access` is supplied — the caller isn't the owner.
   */
  fork(
    id: string,
    atMessage?: number,
    access?: ConversationAccessContext,
  ): Promise<Conversation | null>;
}

/**
 * Conversation metadata — stored as line 1 of the JSONL file.
 *
 * Stage 1: single-owner. The conversation belongs to exactly one user
 * (`ownerId`); workspace is a tool-scoping concern, not an ownership
 * one. Sharing and multi-participant semantics are deferred to Stage 4+
 * with explicit policy gates; the previous `visibility` / `participants`
 * fields are gone.
 *
 * No token totals or cost — those are derived from events at read time
 * (see deriveUsageMetrics in event-reconstructor.ts and the index cache).
 * Storing them invited drift bugs where the cached total didn't match
 * what re-aggregating the events would produce.
 */
export interface Conversation {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string | null;
  lastModel: string | null;
  /** User who owns this conversation. The single authorization principal. */
  ownerId: string;
  /**
   * The room this conversation lives in — the binding. Set at create from the
   * first-message room and never mutated (no mid-chat room switching). The
   * conversation is stored under `workspaces/<workspaceId>/conversations/`, so
   * the path is authoritative and this field is the denormalised convenience.
   * The session is walled to this one workspace plus the owner's identity tools.
   * Optional only for legacy records predating the room-owned layout.
   */
  workspaceId?: string;
  /** Arbitrary caller-provided metadata. Stored in JSONL first line, never validated. */
  metadata?: Record<string, unknown>;
  /** File format discriminator. "events" for event-sourced files. Absent for legacy message format. */
  format?: "events";
}

/**
 * MCP `resource_link` content block — references a workspace resource
 * (typically `files://<id>`) by URI. The bytes live in the resource's
 * owning store; the conversation log carries only the link.
 *
 * The runtime rehydrates image links to AI SDK V3 `file` parts at the
 * `model.doStream` boundary so vision content reaches the model without
 * the JSONL ever holding raw bytes.
 */
export interface ResourceLinkContentPart {
  type: "resource_link";
  uri: string;
  mimeType: string;
  name: string;
}

/**
 * User-message content shape — text plus MCP `resource_link` blocks.
 * Narrower than `LanguageModelV3UserMessage["content"]` (which also
 * permits inline file parts): callers persist references, not bytes.
 */
export type UserContentPart = LanguageModelV3TextPart | ResourceLinkContentPart;

interface StoredMessageMetadata {
  skill?: string | null;
  /**
   * Marks a message the reconstructor synthesized rather than one the model
   * or user produced. `"connector_skill_injected"` is the surface-once
   * connector-overlay message (paired with `skill`, the overlay name) — the
   * engine inspects this on replay to dedup re-injection. See
   * `event-reconstructor.ts`.
   */
  synthetic?: string;
  toolCalls?: Array<{
    id: string;
    name: string;
    input: Record<string, unknown>;
    output: string;
    ok: boolean;
    ms: number;
    resourceUri?: string;
    resourceLinks?: Array<{
      uri: string;
      name?: string;
      mimeType?: string;
      description?: string;
    }>;
  }>;
  /** Cumulative usage for the assistant turn. Cost is derived at read time. */
  usage?: TokenUsage;
  model?: string;
  llmMs?: number;
  iterations?: number;
  /** Per-call finish reason — surfaces length truncation etc. to the UI. */
  finishReason?: "stop" | "length" | "content-filter" | "tool-calls" | "error" | "other";
  files?: Array<{
    id: string;
    filename: string;
    mimeType: string;
    size: number;
    extracted: boolean;
  }>;
}

interface StoredMessageExtras {
  timestamp: string;
  /** User who sent this message (for multi-user conversations). */
  userId?: string;
  metadata?: StoredMessageMetadata;
}

/**
 * In-memory message shape used by the runtime and event store.
 *
 * For non-user roles, this is `LanguageModelV3Message` plus the platform's
 * timestamp/metadata extras. For user role we widen the content union to
 * include `resource_link` blocks so attached images survive end-to-end as
 * URI references; the runtime rehydrates them to AI SDK `file` parts before
 * calling the model.
 */
export type StoredMessage = StoredMessageExtras &
  (
    | { role: "user"; content: UserContentPart[]; providerOptions?: SharedV3ProviderOptions }
    | Exclude<LanguageModelV3Message, { role: "user" }>
  );

// ---------------------------------------------------------------------------
// Event-sourced conversation events
// ---------------------------------------------------------------------------

export type ConversationEventType =
  | "user.message"
  | "run.start"
  | "llm.response"
  | "tool.start"
  | "tool.done"
  | "tool.progress"
  | "run.done"
  | "run.error"
  | "skills.loaded"
  | "context.assembled"
  | "connector.skill.injected"
  | "metadata.title"
  | "history.compacted"
  | "aux.usage";

export interface UserMessageEvent {
  ts: string;
  type: "user.message";
  /**
   * Persisted content. Text + MCP `resource_link` blocks only — never
   * inline bytes. See `UserContentPart`.
   */
  content: UserContentPart[];
  userId?: string;
  files?: Array<{
    id: string;
    filename: string;
    mimeType: string;
    size: number;
    extracted: boolean;
  }>;
}

export interface RunStartEvent {
  ts: string;
  type: "run.start";
  runId: string;
  model: string;
  /** Present only when logging.level is "debug". */
  systemPrompt?: string;
  /** Present only when logging.level is "debug". */
  messages?: unknown[];
  /** Present only when logging.level is "debug". */
  toolSchemas?: string[];
}

export interface LlmResponseEvent {
  ts: string;
  type: "llm.response";
  runId: string;
  model: string;
  /**
   * V3 content blocks. Includes `text`, `tool-call`, and `reasoning`
   * (extended thinking) parts. Reasoning blocks are surfaced to the UI
   * collapsed-by-default; bare absence on a turn with non-stop
   * finishReason is what indicates a real empty turn.
   */
  content: LanguageModelV3Content[];
  /** Token usage for this single LLM call (canonical AI SDK V3 shape). */
  usage: TokenUsage;
  llmMs: number;
  /**
   * Per-call finish reason from the provider (AI SDK V3 unified value).
   * Optional for backward-compat with conversations recorded before this
   * field existed.
   */
  finishReason?: "stop" | "length" | "content-filter" | "tool-calls" | "error" | "other";
}

export interface ToolStartEvent {
  ts: string;
  type: "tool.start";
  runId: string;
  name: string;
  id: string;
  /** Present only when logging.level is "debug". */
  input?: unknown;
}

export interface ToolDoneEvent {
  ts: string;
  type: "tool.done";
  runId: string;
  name: string;
  id: string;
  ok: boolean;
  ms: number;
  /**
   * Full tool output text (audience-filtered). Always persisted — it drives
   * the UI/display and the conversation record.
   */
  output?: string;
  /**
   * Bounded text the MODEL saw on the live turn, present only when it differs
   * from `output` (i.e. the result exceeded the model-context bound). History
   * replay uses this verbatim so the model's replayed view matches its live
   * view; when absent (small result, or a legacy event) replay bounds
   * `output` at read time. See boundToolResultForModel.
   */
  modelOutput?: string;
  /**
   * Static inline-binding resource annotation (`resourceUri`) and the MCP
   * `resource_link` blocks (`resourceLinks`) surfaced from the tool result.
   * Persisted so a reopened conversation rehydrates its `artifact://` viewer
   * panels — the engine emits these on the live event, and the reader/UI already
   * consume them, but without persisting them a reloaded conversation loses the
   * references.
   */
  resourceUri?: string;
  resourceLinks?: ResourceLinkInfo[];
}

export interface ToolProgressEvent {
  ts: string;
  type: "tool.progress";
  runId: string;
  id: string;
  message: string;
}

export interface RunDoneEvent {
  ts: string;
  type: "run.done";
  runId: string;
  stopReason: string;
  totalMs: number;
}

export interface RunErrorEvent {
  ts: string;
  type: "run.error";
  runId: string;
  error: string;
  errorType: string;
}

export interface TitleChangeEvent {
  ts: string;
  type: "metadata.title";
  title: string | null;
}

export interface SkillsLoadedEvent {
  ts: string;
  type: "skills.loaded";
  runId: string;
  skills: SkillsLoadedEntry[];
  totalTokens: number;
}

export interface ContextAssembledEvent {
  ts: string;
  type: "context.assembled";
  runId: string;
  sources: ContextAssembledSource[];
  excluded: ContextAssembledSource[];
  totalTokens: number;
  modelMaxContext?: number;
  headroomTokens?: number;
}

/**
 * Recorded when the runtime folds the oldest turns of a long conversation into
 * a single summary to bound context growth. The event is appended after all the
 * turns it summarizes; `compactedThroughTs` is the boundary — on replay, every
 * event with `ts < compactedThroughTs` is represented by `summary`, and turns at
 * or after it replay verbatim. Multiple compactions can accumulate; reconstruction
 * honors only the most recent (its summary already subsumes the earlier ones).
 * See `conversation/compaction.ts`.
 */
export interface HistoryCompactedEvent {
  ts: string;
  type: "history.compacted";
  /** Natural-language summary of every turn before `compactedThroughTs`. */
  summary: string;
  /** Boundary: events strictly before this timestamp are summarized. */
  compactedThroughTs: string;
  /** How many reconstructed messages the summary replaced (telemetry). */
  summarizedMessageCount: number;
}

/**
 * A curated connector-skill overlay surfaced into the conversation for the
 * first time, triggered by a matching connector tool call during a run.
 * The reconstructor turns this event into a synthetic assistant message whose
 * body is the overlay wrapped in `<connector-skill>` containment, carrying
 * `metadata.synthetic = "connector_skill_injected"` + `metadata.skill` so the
 * guidance rides the append-only history from the next turn on AND so the
 * engine can detect it on replay to never re-inject. Emitted at most once per
 * (conversation, skill).
 */
export interface ConnectorSkillInjectedEvent {
  ts: string;
  type: "connector.skill.injected";
  /** The connector tool call that triggered the surfacing (e.g. `gmail__send`). */
  toolName: string;
  /** The overlay's skill name (matches the materialized manifest `name`). */
  skillName: string;
  /** The overlay body (markdown), surfaced verbatim into history. */
  skillBody: string;
  /** Scope label for containment / telemetry. Always `"connector"` in v1. */
  scope: string;
}

/**
 * Token usage for a forked model call that is NOT a conversation turn — the
 * compaction summarizer and the auto-title generator. These run the `fast`
 * slot outside the agentic loop and so emit no `llm.response`; without this
 * event their cost is invisible to the usage aggregator. It carries no
 * content (the produced text lands elsewhere — the summary seed, the title),
 * and reconstruction skips it, so it never becomes a message.
 */
export interface AuxUsageEvent {
  ts: string;
  type: "aux.usage";
  /** Which forked call produced this usage. */
  source: "compaction" | "title" | "briefing";
  model: string;
  usage: TokenUsage;
  llmMs: number;
}

/** Discriminated union of all conversation event types. */
export type ConversationEvent =
  | UserMessageEvent
  | RunStartEvent
  | LlmResponseEvent
  | ToolStartEvent
  | ToolDoneEvent
  | ToolProgressEvent
  | RunDoneEvent
  | RunErrorEvent
  | SkillsLoadedEvent
  | ContextAssembledEvent
  | ConnectorSkillInjectedEvent
  | TitleChangeEvent
  | HistoryCompactedEvent
  | AuxUsageEvent;
