/**
 * Generates `src/theme/tokens.generated.css` (the shell's `:root`/`.dark`
 * blocks) from the canonical palette. Run via `bun run gen:theme`.
 *
 * The output is committed so the build works without a pre-step, and is
 * reproducible — `bun run gen:theme && git diff --exit-code` is the freshness
 * guard. Edit `src/theme/palette.ts`, never this output.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { paletteToRootCss } from "../src/theme/projections.ts";

const header = `/* AUTO-GENERATED by scripts/gen-theme-css.ts — do not edit.
   Source of truth: src/theme/palette.ts. Run \`bun run gen:theme\` to regenerate. */\n\n`;

const outPath = join(import.meta.dir, "..", "src", "theme", "tokens.generated.css");
writeFileSync(outPath, header + paletteToRootCss());
console.log(`wrote ${outPath}`);
