/**
 * Tests that UserStore correctly handles all user ID formats.
 *
 * User IDs come from different providers:
 * - Local auth: usr_<random> (generated by generateUserId)
 * - OIDC: usr_oidc_<hash> (generated by deriveOidcUserId)
 * - WorkOS: user_<workos_id> (raw WorkOS user IDs)
 *
 * UserStore.list() must return ALL users regardless of ID format.
 */

import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { rmSync } from "node:fs";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { UserStore } from "../../../src/identity/user.ts";

let workDir: string;
let store: UserStore;

beforeAll(async () => {
  workDir = await mkdtemp(join(tmpdir(), "nb-user-id-test-"));
  store = new UserStore(workDir);
});

afterAll(() => {
  rmSync(workDir, { recursive: true, force: true });
});

describe("UserStore handles all ID formats", () => {
  it("creates and lists a local auth user (usr_ prefix)", async () => {
    const user = await store.create({
      email: "local@test.com",
      displayName: "Local User",
      orgRole: "member",
    });
    expect(user.id).toMatch(/^usr_/);

    const all = await store.list();
    expect(all.some((u) => u.email === "local@test.com")).toBe(true);
  });

  it("creates and lists an OIDC user (usr_oidc_ prefix)", async () => {
    const user = await store.create({
      id: "usr_oidc_abc123def456",
      email: "oidc@test.com",
      displayName: "OIDC User",
      orgRole: "member",
    });
    expect(user.id).toBe("usr_oidc_abc123def456");

    const all = await store.list();
    expect(all.some((u) => u.email === "oidc@test.com")).toBe(true);
  });

  it("creates and lists a WorkOS user (user_ prefix)", async () => {
    const user = await store.create({
      id: "user_01ABC123DEF456",
      email: "workos@test.com",
      displayName: "WorkOS User",
      orgRole: "admin",
    });
    expect(user.id).toBe("user_01ABC123DEF456");

    const all = await store.list();
    expect(all.some((u) => u.email === "workos@test.com")).toBe(true);
  });

  it("list() returns all three user types together", async () => {
    const all = await store.list();
    const emails = all.map((u) => u.email);
    expect(emails).toContain("local@test.com");
    expect(emails).toContain("oidc@test.com");
    expect(emails).toContain("workos@test.com");
    expect(all.length).toBeGreaterThanOrEqual(3);
  });

  it("get() works for all ID formats", async () => {
    const local = await store.getByEmail("local@test.com");
    expect(local).not.toBeNull();
    const localById = await store.get(local!.id);
    expect(localById?.email).toBe("local@test.com");

    const oidc = await store.get("usr_oidc_abc123def456");
    expect(oidc?.email).toBe("oidc@test.com");

    const workos = await store.get("user_01ABC123DEF456");
    expect(workos?.email).toBe("workos@test.com");
  });

  it("list() ignores hidden files like .DS_Store", async () => {
    // Create a .DS_Store-like file in the users directory
    const { writeFileSync, mkdirSync } = await import("node:fs");
    const dsStore = join(workDir, "users", ".DS_Store");
    writeFileSync(dsStore, "fake");

    // Also create a non-user directory
    const randomDir = join(workDir, "users", "not-a-user");
    mkdirSync(randomDir, { recursive: true });
    writeFileSync(join(randomDir, "profile.json"), "invalid json");

    const all = await store.list();
    // Should still only have our 3 valid users (the invalid JSON dir is skipped by get())
    expect(all.length).toBe(3);
  });
});
