/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/platform/schemas/_shared.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type TSchema } from "@sinclair/typebox";
export declare function StringEnum<T extends string>(values: readonly T[], options?: {
    description?: string;
}): import("@sinclair/typebox").TUnsafe<T>;
export declare function NumberEnum<T extends number>(values: readonly T[], options?: {
    description?: string;
}): import("@sinclair/typebox").TUnsafe<T>;
/** An optional field an update clears with `null` (src/platform/AGENTS.md §1.3). */
export declare function clearable<T extends TSchema>(schema: T, description: string): import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[T, import("@sinclair/typebox").TNull]>>;
