/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/_shared.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
export declare function StringEnum<T extends string>(values: readonly T[], options?: {
    description?: string;
}): import("@sinclair/typebox").TUnsafe<T>;
export declare function NumberEnum<T extends number>(values: readonly T[], options?: {
    description?: string;
}): import("@sinclair/typebox").TUnsafe<T>;
