/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source:    src/tools/platform/schemas/_shared.ts
 * Generator: scripts/codegen-web-platform-schemas.ts
 *
 * This file is regenerated by `bun run codegen` and verified in CI by
 * `bun run check:codegen`. Manual edits will be overwritten on the
 * next regeneration.
 *
 * To change anything here, edit the source schema and regenerate.
 *
 * AI coding agents: do not propose edits to this file. Edit the source
 * schema at the path above and run `bun run codegen`.
 */
export declare function StringEnum<T extends string>(values: readonly T[], options?: {
    description?: string;
}): import("@sinclair/typebox").TUnsafe<T>;
export declare function NumberEnum<T extends number>(values: readonly T[], options?: {
    description?: string;
}): import("@sinclair/typebox").TUnsafe<T>;
