/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/automations.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
/**
 * Tool input schemas for the automations source. Imported by both the
 * platform in-process source (`src/tools/platform/automations.ts`) and the
 * standalone bundle server (`src/bundles/automations/src/server.ts`) so
 * the two consumers always agree on the wire shape.
 *
 * Shape convention (per src/tools/platform/CLAUDE.md §1.3):
 *
 *   create: { manifest: { ...config }, body: <prompt> }
 *   update: { name, manifest?: Partial<config>, body?: <new prompt> }
 *
 * `manifest` is the persistent automation definition; `body` is the prompt
 * sent to POST /v1/chat on each run — the analog of a skill's markdown
 * body. Operator-only fields (`source`, `bundleName`) are intentionally
 * absent from the LLM-facing schema; they live on the stored type and are
 * set by the runtime, never by an authoring caller.
 */
import { type Static } from "@sinclair/typebox";
export declare const AutomationsCreateInput: import("@sinclair/typebox").TObject<{
    manifest: import("@sinclair/typebox").TObject<{
        name: import("@sinclair/typebox").TString;
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        schedule: import("@sinclair/typebox").TObject<{
            type: import("@sinclair/typebox").TUnsafe<"cron" | "interval">;
            expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        }>;
        enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
        }>>;
    }>;
    body: import("@sinclair/typebox").TString;
}>;
export type AutomationsCreateInput = Static<typeof AutomationsCreateInput>;
export declare const AutomationsUpdateInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
    manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        schedule: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            type: import("@sinclair/typebox").TUnsafe<"cron" | "interval">;
            expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        }>>;
        enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
        }>>;
    }>>;
    body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type AutomationsUpdateInput = Static<typeof AutomationsUpdateInput>;
export declare const AutomationsDeleteInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;
export type AutomationsDeleteInput = Static<typeof AutomationsDeleteInput>;
export declare const AutomationsListInput: import("@sinclair/typebox").TObject<{
    enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
    source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"user" | "agent" | "bundle">>;
}>;
export type AutomationsListInput = Static<typeof AutomationsListInput>;
export declare const AutomationsStatusInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type AutomationsStatusInput = Static<typeof AutomationsStatusInput>;
export declare const AutomationsRunsInput: import("@sinclair/typebox").TObject<{
    automationId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"running" | "success" | "failure" | "timeout" | "cancelled" | "skipped">>;
    since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type AutomationsRunsInput = Static<typeof AutomationsRunsInput>;
export declare const AutomationsRunInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;
export type AutomationsRunInput = Static<typeof AutomationsRunInput>;
export declare const AutomationsCancelInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;
export type AutomationsCancelInput = Static<typeof AutomationsCancelInput>;
/**
 * Status of the most recent automation run, as exposed via the list/
 * summary surface. Mirrors `AutomationRun["status"]` minus `"running"`
 * — the list view shows the most recent COMPLETED run's outcome, never
 * one in flight.
 */
export type AutomationLastRunStatus = "success" | "failure" | "timeout" | "skipped";
/**
 * Summary row returned per automation by `handleList`. Subset of the
 * stored `Automation` shape plus a couple of human-formatted fields the
 * UI surfaces directly. `lastRunAt` / `nextRunAt` are human-relative
 * strings (e.g. "in 2h", "4h ago") — the raw ISO timestamps stay on the
 * stored `Automation`.
 */
export interface AutomationSummary {
    id: string;
    name: string;
    description?: string;
    schedule: string;
    enabled: boolean;
    source: "user" | "agent" | "bundle";
    runCount: number;
    lastRunStatus: AutomationLastRunStatus | null;
    lastRunAt: string | null;
    nextRunAt: string | null;
    disabledAt: string | null;
    disabledReason: string | null;
    estimatedCostPerDay: number;
}
export interface AutomationsListOutput {
    automations: AutomationSummary[];
    total: number;
}
/**
 * Structural mirror of a single AutomationRun record as returned by
 * the handlers. Kept in sync with `AutomationRun` in
 * `bundles/automations/src/types.ts` via the assertion test referenced
 * above. New fields added there MUST also appear here.
 */
export interface AutomationRunRecord {
    id: string;
    automationId: string;
    startedAt: string;
    completedAt?: string;
    status: "running" | "success" | "failure" | "timeout" | "cancelled" | "skipped";
    conversationId?: string;
    inputTokens: number;
    outputTokens: number;
    toolCalls: number;
    iterations: number;
    error?: string;
    transient?: boolean;
    resultPreview?: string;
    stopReason?: "complete" | "max_iterations" | "length" | "content_filter" | "error" | "other";
}
/**
 * Token budget block on a stored automation. Mirror of the
 * `TokenBudget` interface; kept here to avoid a cross-tree import
 * (see top-of-section comment).
 */
export interface AutomationTokenBudget {
    maxInputTokens?: number;
    maxOutputTokens?: number;
    period?: "daily" | "monthly";
}
/**
 * Schedule spec block on a stored automation. Mirror of `ScheduleSpec`.
 */
export interface AutomationScheduleSpec {
    type: "cron" | "interval";
    expression?: string;
    timezone?: string;
    intervalMs?: number;
}
/**
 * Automation detail returned by `handleStatus`. Spreads the stored
 * Automation and overlays a few computed fields the UI consumes
 * directly: humanized schedule + relative-time strings, cost numbers,
 * and undefined→null coercion on optional fields (`tokenBudget`,
 * `budgetResetAt`) so JSON consumers see a consistent shape per field.
 */
export interface AutomationStatusDetail {
    id: string;
    name: string;
    description?: string;
    prompt: string;
    schedule: AutomationScheduleSpec;
    scheduleHuman: string;
    enabled: boolean;
    source: "user" | "agent" | "bundle";
    bundleName?: string;
    ownerId?: string;
    workspaceId?: string;
    model?: string | null;
    skill?: string;
    allowedTools?: string[];
    maxIterations?: number;
    maxInputTokens?: number;
    maxRunDurationMs?: number;
    runCount: number;
    consecutiveErrors: number;
    cumulativeInputTokens: number;
    cumulativeOutputTokens: number;
    tokenBudget: AutomationTokenBudget | null;
    budgetResetAt: string | null;
    lastRunAt?: string;
    lastRunAtHuman: string | null;
    lastRunStatus?: AutomationLastRunStatus;
    nextRunAt?: string;
    nextRunAtHuman: string | null;
    disabledAt?: string;
    disabledReason?: string;
    createdAt: string;
    updatedAt: string;
    actualCostUsd: number;
    estimatedCostPerRun: number;
    estimatedCostPerDay: number;
    estimatedCostPerMonth: number;
}
export interface AutomationsStatusOutput {
    automation: AutomationStatusDetail;
    recentRuns: AutomationRunRecord[];
}
export interface AutomationsRunsOutput {
    runs: AutomationRunRecord[];
    total: number;
}
/**
 * Discriminated union — `handleRun` returns one of two shapes:
 *
 *   { run: AutomationRunRecord }                     when the run finishes
 *                                                    inside the sync-wait
 *                                                    window (~30s default).
 *
 *   { status: "dispatched"; automationId; message }  when the run is still
 *                                                    in flight after the
 *                                                    window. Scheduler keeps
 *                                                    tracking; poll
 *                                                    `automations__runs`
 *                                                    for completion.
 *
 * Both shapes indicate the dispatch succeeded; only an error response
 * indicates failure to dispatch. Consumers MUST narrow before
 * dereferencing `run.*` — `as { run: ... }` is the anti-pattern that
 * caused the production CLI crash this type prevents.
 */
export type AutomationsRunOutput = {
    run: AutomationRunRecord;
} | {
    status: "dispatched";
    automationId: string;
    message: string;
};
export interface AutomationsCancelOutput {
    cancelled: boolean;
    id: string;
    message: string;
}
