/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/platform/schemas/catalog.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import type { Static, TSchema } from "@sinclair/typebox";
export declare const PlatformToolCatalog: {
    readonly nb: {
        readonly manage_tools: {
            readonly input: import("@sinclair/typebox").TObject<{
                add: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                remove: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            }>;
        };
        readonly use_skill: {
            readonly input: import("@sinclair/typebox").TObject<{
                name: import("@sinclair/typebox").TString;
            }>;
        };
    };
    readonly skills: {
        readonly list: {
            readonly input: import("@sinclair/typebox").TObject<{
                scope: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"org" | "workspace" | "user" | "provided">>;
                layer: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<1 | 3>>;
                loading_strategy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"always" | "dynamic">>;
                tool_affinity: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"active" | "disabled">>;
                modified_since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly read: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
                version: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly loading_log: {
            readonly input: import("@sinclair/typebox").TObject<{
                conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                loaded_by: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"always" | "tool_affinity" | "trigger" | "tool_use" | "activation">>;
                since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                until: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly create: {
            readonly input: import("@sinclair/typebox").TObject<{
                scope: import("@sinclair/typebox").TUnsafe<"org" | "workspace" | "user">;
                manifest: import("@sinclair/typebox").TObject<{
                    name: import("@sinclair/typebox").TString;
                    description: import("@sinclair/typebox").TString;
                    loadingStrategy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"always" | "dynamic">>;
                    priority: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                    toolAffinity: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                    triggers: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                    allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                }>;
                body: import("@sinclair/typebox").TString;
                frontmatter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"apply" | "ignore">>;
            }>;
        };
        readonly update: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
                manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                    loadingStrategy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<"always" | "dynamic">, import("@sinclair/typebox").TNull]>>;
                    priority: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TNull]>>;
                    toolAffinity: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>, import("@sinclair/typebox").TNull]>>;
                    triggers: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>, import("@sinclair/typebox").TNull]>>;
                    allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>, import("@sinclair/typebox").TNull]>>;
                }>>;
                body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                body_mode: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"append">, import("@sinclair/typebox").TLiteral<"replace">]>>;
                frontmatter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"apply" | "ignore">>;
            }>;
        };
        readonly delete: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
            }>;
        };
        readonly activate: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
            }>;
        };
        readonly deactivate: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
            }>;
        };
    };
    readonly usage: {
        readonly report: {
            readonly input: import("@sinclair/typebox").TObject<{
                scope: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"org" | "user">>;
                period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"day" | "week" | "month" | "all">>;
                from: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                to: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                groupBy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<"workspace" | "user" | "day" | "model" | "conversation" | "turn" | "origin" | "provider">, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnsafe<"workspace" | "user" | "day" | "model" | "conversation" | "turn" | "origin" | "provider">>]>>;
                stackBy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"workspace" | "user" | "model" | "origin" | "provider">>;
                workspaceId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                userId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                origin: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"chat" | "task" | "system">>;
            }>;
        };
    };
    readonly compose: {
        readonly effective_context: {
            readonly input: import("@sinclair/typebox").TObject<{
                conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                run_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                connector: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly assembled_context: {
            readonly input: import("@sinclair/typebox").TObject<{
                conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                run_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
    };
    readonly tasks: {
        readonly create: {
            readonly input: import("@sinclair/typebox").TObject<{
                manifest: import("@sinclair/typebox").TObject<{
                    skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                    model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                    allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                    maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                    maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                    maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                    tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
                    }>>;
                    inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                    outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                    criteria: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                        id: import("@sinclair/typebox").TString;
                        rule: import("@sinclair/typebox").TString;
                        type: import("@sinclair/typebox").TUnsafe<"boolean" | "score" | "choice">;
                        levels: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                        options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                        pass: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TBoolean, import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TString, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>]>>;
                    }>>>;
                    confidenceThreshold: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                    judge: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                        server: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                    }>>;
                    onPoorResult: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"record" | "notify" | "retry_once">>;
                    name: import("@sinclair/typebox").TString;
                    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                    schedule: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                        type: import("@sinclair/typebox").TUnsafe<"cron" | "interval" | "event" | "once">;
                        expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        at: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        match: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                            source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                            name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                            level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
                        }>>;
                        debounceMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        maxFiresPerHour: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                    }>>;
                    enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                    kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"saved" | "oneoff">>;
                }>;
                body: import("@sinclair/typebox").TString;
            }>;
        };
        readonly update: {
            readonly input: import("@sinclair/typebox").TObject<{
                taskId: import("@sinclair/typebox").TString;
                manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TNull]>>;
                    schedule: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
                        type: import("@sinclair/typebox").TUnsafe<"cron" | "interval" | "event" | "once">;
                        expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        at: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        match: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                            source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                            name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                            level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
                        }>>;
                        debounceMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        maxFiresPerHour: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                    }>, import("@sinclair/typebox").TNull]>>;
                    enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                    skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TNull]>>;
                    model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TNull]>>;
                    allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>, import("@sinclair/typebox").TNull]>>;
                    maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TNull]>>;
                    maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TNull]>>;
                    maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TNull]>>;
                    tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
                        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
                    }>, import("@sinclair/typebox").TNull]>>;
                    inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<Record<string, unknown>>, import("@sinclair/typebox").TNull]>>;
                    outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<Record<string, unknown>>, import("@sinclair/typebox").TNull]>>;
                    criteria: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                        id: import("@sinclair/typebox").TString;
                        rule: import("@sinclair/typebox").TString;
                        type: import("@sinclair/typebox").TUnsafe<"boolean" | "score" | "choice">;
                        levels: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                        options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                        pass: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TBoolean, import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TString, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>]>>;
                    }>>, import("@sinclair/typebox").TNull]>>;
                    confidenceThreshold: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TNull]>>;
                    judge: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
                        server: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                    }>, import("@sinclair/typebox").TNull]>>;
                    onPoorResult: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<"record" | "notify" | "retry_once">, import("@sinclair/typebox").TNull]>>;
                }>>;
                body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly delete: {
            readonly input: import("@sinclair/typebox").TObject<{
                taskId: import("@sinclair/typebox").TString;
            }>;
        };
        readonly list: {
            readonly input: import("@sinclair/typebox").TObject<{
                enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"user" | "agent">>;
                kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"all" | "saved" | "oneoff">>;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                cursor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly status: {
            readonly input: import("@sinclair/typebox").TObject<{
                taskId: import("@sinclair/typebox").TString;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            }>;
        };
        readonly runs: {
            readonly input: import("@sinclair/typebox").TObject<{
                taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                label: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"Succeeded" | "Poor result" | "Needs review" | "Failed" | "Skipped" | "Cancelled">>;
                verdict: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"pass" | "fail" | "uncertain" | "not_assessed">>;
                since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                before: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                excludeBatchRuns: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            }>;
        };
        readonly run: {
            readonly input: import("@sinclair/typebox").TObject<{
                taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                definition: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                    manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                        skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                        tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                            maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                            period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
                        }>>;
                        inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                        outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                        criteria: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                            id: import("@sinclair/typebox").TString;
                            rule: import("@sinclair/typebox").TString;
                            type: import("@sinclair/typebox").TUnsafe<"boolean" | "score" | "choice">;
                            levels: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                            options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                            pass: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TBoolean, import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TString, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>]>>;
                        }>>>;
                        confidenceThreshold: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                        judge: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                            server: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                            id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                            options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                        }>>;
                        onPoorResult: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"record" | "notify" | "retry_once">>;
                    }>>;
                    body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                }>>;
                input: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<unknown>>;
                idempotencyKey: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly cancel: {
            readonly input: import("@sinclair/typebox").TObject<{
                runId: import("@sinclair/typebox").TString;
            }>;
        };
        readonly assess: {
            readonly input: import("@sinclair/typebox").TObject<{
                runId: import("@sinclair/typebox").TString;
                taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                verdict: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"pass" | "fail">>;
                note: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                reassess: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
            }>;
        };
    };
    readonly conversations: {
        readonly list: {
            readonly input: import("@sinclair/typebox").TObject<{
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                cursor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                search: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                sortBy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"created" | "updated">>;
                dateFrom: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                dateTo: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly get: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                expand: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"metadata" | "messages" | "full">>;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            }>;
        };
        readonly search: {
            readonly input: import("@sinclair/typebox").TObject<{
                query: import("@sinclair/typebox").TString;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            }>;
        };
        readonly update: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                title: import("@sinclair/typebox").TString;
            }>;
        };
        readonly fork: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                atMessage: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            }>;
        };
        readonly stats: {
            readonly input: import("@sinclair/typebox").TObject<{
                period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"day" | "week" | "month" | "all">>;
            }>;
        };
        readonly export: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                format: import("@sinclair/typebox").TUnsafe<"markdown" | "json">;
            }>;
        };
    };
    readonly notifications: {
        readonly list: {
            readonly input: import("@sinclair/typebox").TObject<{
                unreadOnly: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
                source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                after: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                before: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
                ids: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                query: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                order: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"asc" | "desc">>;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            }>;
        };
        readonly mark_read: {
            readonly input: import("@sinclair/typebox").TObject<{
                ids: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>;
            }>;
        };
        readonly settings: {
            readonly input: import("@sinclair/typebox").TObject<{}>;
        };
        readonly set_source_level: {
            readonly input: import("@sinclair/typebox").TObject<{
                source: import("@sinclair/typebox").TString;
                maxLevel: import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">;
            }>;
        };
        readonly set_routes: {
            readonly input: import("@sinclair/typebox").TObject<{
                routes: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                    id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                    match: import("@sinclair/typebox").TObject<{
                        source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                        level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
                    }>;
                    deliver: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
                        kind: import("@sinclair/typebox").TLiteral<"tool">;
                        tool: import("@sinclair/typebox").TString;
                        input: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
                    }>, import("@sinclair/typebox").TObject<{
                        kind: import("@sinclair/typebox").TLiteral<"agent">;
                        task: import("@sinclair/typebox").TString;
                    }>]>>;
                }>>;
            }>;
        };
    };
    readonly files: {
        readonly list: {
            readonly input: import("@sinclair/typebox").TObject<{
                folderId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                recursive: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
                query: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                kinds: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnsafe<"image" | "document" | "data" | "font" | "other">>>;
                sources: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnsafe<"chat" | "agent" | "app" | "manual">>>;
                conversationId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                runId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                createdAfter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                createdBefore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                mimeType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                sort: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"createdAt" | "filename" | "size">>;
                order: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"asc" | "desc">>;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                offset: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            }>;
        };
        readonly search: {
            readonly input: import("@sinclair/typebox").TObject<{
                query: import("@sinclair/typebox").TString;
                tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                mimeType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            }>;
        };
        readonly read: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
            }>;
        };
        readonly create: {
            readonly input: import("@sinclair/typebox").TObject<{
                manifest: import("@sinclair/typebox").TObject<{
                    filename: import("@sinclair/typebox").TString;
                    folder: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                    mimeType: import("@sinclair/typebox").TString;
                    tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                }>;
                body: import("@sinclair/typebox").TString;
                encoding: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"text" | "base64">>;
            }>;
        };
        readonly info: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
            }>;
        };
        readonly tag: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
                add: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                remove: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            }>;
        };
        readonly delete: {
            readonly input: import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
            }>;
        };
    };
};
export type PlatformToolCatalog = typeof PlatformToolCatalog;
export type ToolSource = keyof PlatformToolCatalog;
export type ToolName<S extends ToolSource> = keyof PlatformToolCatalog[S];
export type ToolInput<S extends string, T extends string> = S extends ToolSource ? T extends ToolName<S> ? PlatformToolCatalog[S][T] extends {
    input: infer Sch;
} ? Sch extends TSchema ? Static<Sch> : Record<string, unknown> : Record<string, unknown> : Record<string, unknown> : Record<string, unknown>;
