/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/compose.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
export declare const ComposeEffectiveContextInput: import("@sinclair/typebox").TObject<{
    conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    run_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    bundle: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type ComposeEffectiveContextInput = Static<typeof ComposeEffectiveContextInput>;
export declare const ComposeAssembledContextInput: import("@sinclair/typebox").TObject<{
    conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    run_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type ComposeAssembledContextInput = Static<typeof ComposeAssembledContextInput>;
/**
 * One row of a run's assembled context, as recorded in the
 * `context.assembled` event. `kind` is a free-form source discriminator
 * (`system_prompt`, `tool_descriptions`, `skills`, `history`); the other
 * fields are populated per kind (`count` for tools/skills, `turns` /
 * `compacted` for history).
 */
export interface AssembledContextSource {
    kind: string;
    tokens: number;
    count?: number;
    turns?: number;
    compacted?: boolean;
}
/**
 * One layer-3 skill that loaded for the run, projected from the
 * `skills.loaded` event with provenance for why it loaded.
 */
export interface AssembledContextSkill {
    id: string;
    scope: "org" | "workspace" | "user" | "bundle";
    tokens: number;
    loadedBy: "always" | "tool_affinity";
    reason: string;
}
/**
 * `compose__assembled_context` response — the recorded context digest for
 * a conversation's run (the most recent by default). A pure read of the
 * run's already-emitted `context.assembled` + `skills.loaded` events; no
 * recomposition. `runId` / `ts` are `null` when the conversation exists but
 * no run has recorded assembled-context telemetry yet.
 */
export interface ComposeAssembledContextOutput {
    conversationId: string;
    runId: string | null;
    ts: string | null;
    sources: AssembledContextSource[];
    excluded: AssembledContextSource[];
    totalTokens: number;
    skills: AssembledContextSkill[];
    /** Present only when the run recorded them (not emitted on current runs). */
    modelMaxContext?: number;
    headroomTokens?: number;
}
/**
 * One entry within a traced layer that aggregates operator-authored items
 * (apps, layer-3 skills). Mirrors the runtime `TracedSubItem` minus the
 * free-form `metadata` bag — the inspector renders id/source/bundle only.
 */
export interface TracedSubItemView {
    kind: "app" | "layer3_skill";
    id: string;
    source: string;
    bundle?: string;
}
/**
 * One section of the composed system prompt with provenance and body — the
 * web-facing projection of the runtime `TracedLayer`. Carries `text` (the
 * exact composed body of the layer) so the context inspector's reading pane
 * can show what actually entered the window. Lighter consumers may ignore
 * `text`; it is the largest field and only the inspector renders it.
 */
export interface TracedLayerView {
    kind: string;
    segment: "stable" | "volatile";
    id: string;
    source: string;
    tokens: number;
    text: string;
    bundle?: string;
    subItems?: TracedSubItemView[];
}
/**
 * `compose__effective_context` response as consumed by the context inspector.
 * The runtime tool also returns the full composed `text` at the top level;
 * that field is intentionally absent here — the inspector reads each layer's
 * `text` and never the whole-prompt blob.
 */
export interface ComposeEffectiveContextOutput {
    mode: "live" | "historical";
    conversationId: string;
    totalTokens: number;
    layers: TracedLayerView[];
    warnings: string[];
}
