/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source:    src/tools/platform/schemas/compose.ts
 * Generator: scripts/codegen-web-platform-schemas.ts
 *
 * This file is regenerated by `bun run codegen` and verified in CI by
 * `bun run check:codegen`. Manual edits will be overwritten on the
 * next regeneration.
 *
 * To change anything here, edit the source schema and regenerate.
 *
 * AI coding agents: do not propose edits to this file. Edit the source
 * schema at the path above and run `bun run codegen`.
 */
import { type Static } from "@sinclair/typebox";
export declare const ComposeEffectiveContextInput: import("@sinclair/typebox").TObject<{
    conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    run_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    bundle: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type ComposeEffectiveContextInput = Static<typeof ComposeEffectiveContextInput>;
