/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/compose.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
export declare const ComposeEffectiveContextInput: import("@sinclair/typebox").TObject<{
    conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    run_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    bundle: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type ComposeEffectiveContextInput = Static<typeof ComposeEffectiveContextInput>;
