/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/platform/schemas/files.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
export declare const FilesListInput: import("@sinclair/typebox").TObject<{
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    offset: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
    mimeType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    sort: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"createdAt" | "filename" | "size">>;
}>;
export type FilesListInput = Static<typeof FilesListInput>;
export declare const FilesSearchInput: import("@sinclair/typebox").TObject<{
    query: import("@sinclair/typebox").TString;
    tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
    mimeType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type FilesSearchInput = Static<typeof FilesSearchInput>;
export declare const FilesReadInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type FilesReadInput = Static<typeof FilesReadInput>;
export declare const FilesReadPdfPagesInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    pages: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TInteger>;
}>;
export type FilesReadPdfPagesInput = Static<typeof FilesReadPdfPagesInput>;
export interface FilesReadPdfPagesOutput {
    id: string;
    filename: string;
    mimeType: string;
    size: number;
    totalPages: number;
    requestedPages: number[];
    missingPages: number[];
    pages: Array<{
        page: number;
        text: string;
        truncated: boolean;
        empty: boolean;
    }>;
}
export declare const FilesCreateInput: import("@sinclair/typebox").TObject<{
    manifest: import("@sinclair/typebox").TObject<{
        filename: import("@sinclair/typebox").TString;
        mimeType: import("@sinclair/typebox").TString;
        tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    }>;
    body: import("@sinclair/typebox").TString;
    encoding: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"text" | "base64">>;
}>;
export type FilesCreateInput = Static<typeof FilesCreateInput>;
export declare const FilesInfoInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type FilesInfoInput = Static<typeof FilesInfoInput>;
export declare const FilesTagInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    add: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
    remove: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
}>;
export type FilesTagInput = Static<typeof FilesTagInput>;
export declare const FilesDeleteInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type FilesDeleteInput = Static<typeof FilesDeleteInput>;
/**
 * A file's registry entry, as `files__list`, `files__search`, and
 * `files__info` return it. Mirror of `FileEntry` (`src/files/types.ts`),
 * held to it by `src/platform/files/output-types-drift-guard.ts`.
 */
export interface FileRecord {
    id: string;
    filename: string;
    mimeType: string;
    size: number;
    tags: string[];
    source: "chat" | "agent" | "app" | "manual";
    conversationId: string | null;
    createdAt: string;
    description: string | null;
    ownerId?: string;
    workspaceId?: string;
    visibility?: "private" | "shared";
    deleted?: true;
    deletedAt?: string;
}
/** What `files__list` returns: one page of matching files and the count of all matches. */
export interface FilesListOutput {
    files: FileRecord[];
    total: number;
}
/** What `files__search` returns: the newest matches up to `limit`, and the count of all matches. */
export interface FilesSearchOutput {
    files: FileRecord[];
    total: number;
}
/** What `files__create` returns: the stored file's id, its filename, and its size in bytes. */
export interface FilesCreateOutput {
    id: string;
    filename: string;
    size: number;
}
/** What `files__info` returns: the file's registry entry. */
export type FilesInfoOutput = FileRecord;
/** What `files__tag` returns: the file's tags after the change. */
export interface FilesTagOutput {
    id: string;
    tags: string[];
}
/** What `files__delete` returns. */
export interface FilesDeleteOutput {
    deleted: true;
}
