/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source:    src/tools/platform/schemas/home.ts
 * Generator: scripts/codegen-web-platform-schemas.ts
 *
 * This file is regenerated by `bun run codegen` and verified in CI by
 * `bun run check:codegen`. Manual edits will be overwritten on the
 * next regeneration.
 *
 * To change anything here, edit the source schema and regenerate.
 *
 * AI coding agents: do not propose edits to this file. Edit the source
 * schema at the path above and run `bun run codegen`.
 */
import { type Static } from "@sinclair/typebox";
export declare const HomeActivityInput: import("@sinclair/typebox").TObject<{
    since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    until: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    category: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"conversations" | "bundles" | "tools" | "errors">>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type HomeActivityInput = Static<typeof HomeActivityInput>;
