/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/hooks.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
/** No arguments: the workspace comes from the request, never from the caller. */
export declare const HooksListInput: import("@sinclair/typebox").TObject<{}>;
export declare const HooksRotateInput: import("@sinclair/typebox").TObject<{
    connector: import("@sinclair/typebox").TString;
    vendor: import("@sinclair/typebox").TString;
    confirm: import("@sinclair/typebox").TString;
}>;
