/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source:    src/tools/platform/schemas/instructions.ts
 * Generator: scripts/codegen-web-platform-schemas.ts
 *
 * This file is regenerated by `bun run codegen` and verified in CI by
 * `bun run check:codegen`. Manual edits will be overwritten on the
 * next regeneration.
 *
 * To change anything here, edit the source schema and regenerate.
 *
 * AI coding agents: do not propose edits to this file. Edit the source
 * schema at the path above and run `bun run codegen`.
 */
import { type Static } from "@sinclair/typebox";
export declare const InstructionsWriteInput: import("@sinclair/typebox").TObject<{
    scope: import("@sinclair/typebox").TUnsafe<"org" | "workspace">;
    body: import("@sinclair/typebox").TString;
}>;
export type InstructionsWriteInput = Static<typeof InstructionsWriteInput>;
