/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/notifications.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
/**
 * Canonical urgency vocabulary, ordered least to most urgent. Single source of
 * truth: the TypeBox enum below, the {@link NotificationLevel} type, and the
 * domain's rank map (`src/notifications/types.ts`) all derive from this array,
 * so a fourth level is added in exactly one place.
 *
 * It lives here rather than in `src/notifications/` for the same reason
 * `USAGE_GROUP_BYS` does: this directory is the one the web codegen compiles,
 * and it must stay self-contained.
 */
export declare const NOTIFICATION_LEVELS: readonly ["info", "attention", "urgent"];
export type NotificationLevel = (typeof NOTIFICATION_LEVELS)[number];
/** Page sizes for every notification list — the tool, the store, the REST route. */
export declare const NOTIFICATION_LIST_DEFAULT_LIMIT = 20;
export declare const NOTIFICATION_LIST_MAX_LIMIT = 100;
export declare const NotificationsListInput: import("@sinclair/typebox").TObject<{
    unreadOnly: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
    level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"attention" | "info" | "urgent">>;
    source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    after: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type NotificationsListInput = Static<typeof NotificationsListInput>;
export declare const NotificationsMarkReadInput: import("@sinclair/typebox").TObject<{
    ids: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>;
}>;
export type NotificationsMarkReadInput = Static<typeof NotificationsMarkReadInput>;
/**
 * The wire shape of one inbox item — the agent's tool and the web inbox's REST
 * route return the same projection, so the two can never disagree about what
 * an item is.
 *
 * It is a flattening of the stored record, not a subset with a policy in it:
 * the presentation block is resolved with its defaults applied and the
 * envelope's identity fields are lifted beside it.
 *
 * `data` is the emitting server's own structured payload, forwarded verbatim.
 * No runtime code reads a field of it — it crosses this boundary the way a
 * tool result's `structuredContent` does, and carries exactly as much
 * authority: it is data a connector wrote, not an instruction.
 */
export interface NotificationView {
    /** `<source>:<eventId>`. What `notifications__mark_read` is addressed with. */
    id: string;
    /** Monotonic position in this workspace's inbox. */
    seq: number;
    /** The connector that emitted it, stamped by the runtime. */
    source: string;
    /** The server's own event name. */
    name: string;
    level: NotificationLevel;
    title: string;
    subject?: string;
    body?: string;
    link?: {
        resource: string;
    };
    /** When the emitting server says the fact happened. */
    timestamp: string;
    /** When this runtime wrote it. */
    receivedAt: string;
    readAt?: string;
    data: Record<string, unknown>;
}
export interface NotificationsListOutput {
    notifications: NotificationView[];
    /**
     * Highest `seq` in this page, absent when the page is empty. Pass it back as
     * `after` to get what arrives after it. It does not walk backwards: with
     * more unread items than `limit`, the older ones are reached by raising
     * `limit`, or by the workspace notifications endpoint, which pages
     * ascending.
     */
    cursor?: number;
}
export interface NotificationsMarkReadOutput {
    /** Ids that were unread in this workspace and are now read. */
    marked: string[];
    /**
     * Ids that named nothing markable here — unknown, already read, malformed,
     * or belonging to another workspace, which this session cannot reach.
     */
    skipped: string[];
}
