/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/skills.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
export declare const SkillsListInput: import("@sinclair/typebox").TObject<{
    scope: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"user" | "bundle" | "org" | "workspace">>;
    layer: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<3 | 1>>;
    type: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    tool_affinity: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"active" | "draft" | "disabled" | "archived">>;
    modified_since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type SkillsListInput = Static<typeof SkillsListInput>;
export declare const SkillsReadInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsReadInput = Static<typeof SkillsReadInput>;
export declare const SkillsActiveForInput: import("@sinclair/typebox").TObject<{
    conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type SkillsActiveForInput = Static<typeof SkillsActiveForInput>;
export declare const SkillsLoadingLogInput: import("@sinclair/typebox").TObject<{
    conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    skill_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    until: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type SkillsLoadingLogInput = Static<typeof SkillsLoadingLogInput>;
export declare const SkillsCreateInput: import("@sinclair/typebox").TObject<{
    scope: import("@sinclair/typebox").TUnsafe<"user" | "org" | "workspace">;
    manifest: import("@sinclair/typebox").TObject<{
        name: import("@sinclair/typebox").TString;
        description: import("@sinclair/typebox").TString;
        type: import("@sinclair/typebox").TUnsafe<"skill" | "context">;
        priority: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"active" | "draft" | "disabled" | "archived">>;
        version: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            keywords: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            triggers: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            category: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        }>>;
    }>;
    body: import("@sinclair/typebox").TString;
}>;
export type SkillsCreateInput = Static<typeof SkillsCreateInput>;
export declare const SkillsUpdateInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        type: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"skill" | "context">>;
        priority: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"active" | "draft" | "disabled" | "archived">>;
        version: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            keywords: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            triggers: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            category: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            tags: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        }>>;
    }>>;
    body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type SkillsUpdateInput = Static<typeof SkillsUpdateInput>;
export declare const SkillsDeleteInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsDeleteInput = Static<typeof SkillsDeleteInput>;
export declare const SkillsActivateInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsActivateInput = Static<typeof SkillsActivateInput>;
export declare const SkillsDeactivateInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsDeactivateInput = Static<typeof SkillsDeactivateInput>;
export declare const SkillsMoveScopeInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    target_scope: import("@sinclair/typebox").TUnsafe<"user" | "org" | "workspace">;
}>;
export type SkillsMoveScopeInput = Static<typeof SkillsMoveScopeInput>;
/** Tier a skill lives in. */
export type SkillScope = "org" | "workspace" | "user" | "bundle";
/** Skill layer per the loading-strategy spec. */
export type SkillLayer = 1 | 3;
/** Per-skill lifecycle status. */
export type SkillStatus = "active" | "draft" | "disabled" | "archived";
/**
 * Source provenance for a skill — where it came from on disk or via
 * a bundle. Optional fields; at least one is populated.
 */
export interface SkillSource {
    bundle?: string;
    bundleVersion?: string;
    path?: string;
    uri?: string;
}
/**
 * Row returned per skill by `skills__list`. The summary surface for the
 * settings UI and the agent's `skills__list` enumeration.
 */
export interface SkillSummary {
    id: string;
    name: string;
    layer: SkillLayer;
    scope: SkillScope;
    status: SkillStatus;
    type?: string;
    tokens: number;
    source: SkillSource;
    description?: string;
    modifiedAt?: string;
    loadingStrategy?: string;
    appliesToTools?: string[];
    priority?: number;
}
export interface SkillsListOutput {
    skills: SkillSummary[];
}
/**
 * Full skill detail returned by `skills__read` — includes the markdown
 * body and the full manifest metadata block.
 */
export interface SkillDetail {
    id: string;
    content: string;
    layer: SkillLayer;
    scope: SkillScope;
    source: SkillSource;
    metadata: {
        name: string;
        description?: string;
        type?: string;
        priority?: number;
        loadingStrategy?: string;
        appliesToTools?: string[];
        status?: string;
        overrides?: Array<{
            bundle?: string;
            skill?: string;
            reason: string;
        }>;
        derivedFrom?: string;
    };
    modifiedAt?: string;
}
/** `SkillsReadOutput` is the detail itself — no wrapper envelope. */
export type SkillsReadOutput = SkillDetail;
/**
 * Single entry in the `skills__active_for` response — one currently-
 * active layer-3 skill for the named conversation, with provenance for
 * why it loaded.
 */
export interface ActiveSkillEntry {
    id: string;
    layer: 3;
    scope: SkillScope;
    tokens: number;
    loadedBy: "always" | "tool_affinity";
    reason: string;
}
export interface SkillsActiveForOutput {
    active: ActiveSkillEntry[];
    conversationId: string;
}
