/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/platform/schemas/skills.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
/**
 * The priority band a TOOL caller may write — narrower than the on-disk schema,
 * which allows 0–100 because the platform's own vendored core skills live in
 * 0–10. That band is not decoration: `partitionContextSkills` renders a
 * non-connector skill at or below `CORE_PRIORITY_THRESHOLD` raw in Layer 0
 * rather than inside `<context-skill>` containment, so it is the boundary
 * separating first-party identity from tenant-authored prose.
 *
 * Exported so the one place that admits manifest fields from outside this
 * schema — a pasted SKILL.md, validated against the on-disk contract — can
 * check against this band rather than restate it.
 */
export declare const SkillPriority: import("@sinclair/typebox").TNumber;
export declare const SkillsListInput: import("@sinclair/typebox").TObject<{
    scope: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"user" | "bundle" | "org" | "workspace">>;
    layer: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<3 | 1>>;
    loading_strategy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"always" | "dynamic">>;
    tool_affinity: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"active" | "disabled">>;
    modified_since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type SkillsListInput = Static<typeof SkillsListInput>;
export declare const SkillsReadInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    version: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type SkillsReadInput = Static<typeof SkillsReadInput>;
export declare const SkillsLoadingLogInput: import("@sinclair/typebox").TObject<{
    conversation_id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    loaded_by: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"always" | "tool_affinity" | "trigger" | "tool_use" | "activation">>;
    since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    until: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type SkillsLoadingLogInput = Static<typeof SkillsLoadingLogInput>;
export declare const SkillsCreateInput: import("@sinclair/typebox").TObject<{
    scope: import("@sinclair/typebox").TUnsafe<"user" | "org" | "workspace">;
    manifest: import("@sinclair/typebox").TObject<{
        name: import("@sinclair/typebox").TString;
        description: import("@sinclair/typebox").TString;
        loadingStrategy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"always" | "dynamic">>;
        priority: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        toolAffinity: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        triggers: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
    }>;
    body: import("@sinclair/typebox").TString;
    frontmatter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"apply" | "ignore">>;
}>;
export type SkillsCreateInput = Static<typeof SkillsCreateInput>;
export declare const SkillsUpdateInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        loadingStrategy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"always" | "dynamic">>;
        priority: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        toolAffinity: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        triggers: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
    }>>;
    body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    body_mode: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"append">, import("@sinclair/typebox").TLiteral<"replace">]>>;
    frontmatter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"apply" | "ignore">>;
}>;
export type SkillsUpdateInput = Static<typeof SkillsUpdateInput>;
export declare const SkillsHistoryInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsHistoryInput = Static<typeof SkillsHistoryInput>;
export declare const SkillsRestoreInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    version: import("@sinclair/typebox").TString;
}>;
export type SkillsRestoreInput = Static<typeof SkillsRestoreInput>;
export declare const SkillsDeleteInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsDeleteInput = Static<typeof SkillsDeleteInput>;
export declare const SkillsSetStatusInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    status: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"active">, import("@sinclair/typebox").TLiteral<"disabled">]>;
}>;
export type SkillsSetStatusInput = Static<typeof SkillsSetStatusInput>;
export declare const SkillsActivateInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsActivateInput = Static<typeof SkillsActivateInput>;
export declare const SkillsDeactivateInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
}>;
export type SkillsDeactivateInput = Static<typeof SkillsDeactivateInput>;
export declare const UseSkillInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;
export type UseSkillInput = Static<typeof UseSkillInput>;
/** Tier a skill lives in. */
export type SkillScope = "org" | "workspace" | "user" | "bundle";
/** Skill layer per the loading-strategy spec. */
export type SkillLayer = 1 | 3;
/** Per-skill enablement state. */
export type SkillStatus = "active" | "disabled";
/**
 * Source provenance for a skill — where it came from on disk or via
 * a connector. Optional fields; at least one is populated.
 */
export interface SkillSource {
    connector?: string;
    connectorVersion?: string;
    path?: string;
    uri?: string;
}
/**
 * Computed loading visibility: whether any loader path reaches a skill
 * (`wouldLoad`) and the mechanism by which it loads. `mechanism: "none"`
 * (`wouldLoad: false`) flags a dead skill — no strategy, no triggers, no tool
 * affinity — that would otherwise be silently inert. Derived by
 * `resolveLoadingMechanism`, not stored on disk.
 */
export interface SkillLoading {
    wouldLoad: boolean;
    mechanism: "always" | "tool_affinity" | "trigger" | "none";
}
/**
 * Row returned per skill by `skills__list`. The summary surface for the
 * settings UI and the agent's `skills__list` enumeration.
 */
export interface SkillSummary {
    id: string;
    name: string;
    layer: SkillLayer;
    scope: SkillScope;
    status: SkillStatus;
    tokens: number;
    source: SkillSource;
    description?: string;
    modifiedAt?: string;
    loadingStrategy?: string;
    toolAffinity?: string[];
    triggers?: string[];
    priority?: number;
    loading?: SkillLoading;
}
export interface SkillsListOutput {
    skills: SkillSummary[];
}
/**
 * Full skill detail returned by `skills__read` — includes the markdown
 * body and the full manifest metadata block.
 */
export interface SkillDetail {
    id: string;
    content: string;
    layer: SkillLayer;
    scope: SkillScope;
    source: SkillSource;
    metadata: {
        name: string;
        description?: string;
        priority?: number;
        loadingStrategy?: string;
        toolAffinity?: string[];
        triggers?: string[];
        status?: string;
    };
    modifiedAt?: string;
}
/** `SkillsReadOutput` is the detail itself — no wrapper envelope. */
export type SkillsReadOutput = SkillDetail;
/**
 * Result of a write — `skills__create` and `skills__update` share it.
 *
 * `loading` answers the question a skill exists to answer, at the moment it is
 * written: a skill that reaches no loader path is reported here rather than
 * discovered later as silence. `frontmatterApplied` names the on-disk fields
 * taken from a pasted SKILL.md, so a caller whose manifest was overridden by
 * the document it handed over is told which fields moved and why.
 */
export interface SkillsWriteOutput {
    id: string;
    name: string;
    scope: string;
    loadingStrategy?: string;
    loading?: SkillLoading;
    /** Absent when the body carried no frontmatter, or when `frontmatter: "ignore"`. */
    frontmatterApplied?: string[];
}
/**
 * `nb__use_skill` result. `loaded` delivers the skill (body rides the result's
 * `content`, not this typed envelope); `already_loaded` is the dedupe note —
 * the body is already in the conversation's context, so none is re-delivered.
 */
export type SkillsUseOutput = {
    status: "loaded";
    name: string;
    scope: string;
    tokens: number;
} | {
    status: "already_loaded";
    name: string;
};
