/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/platform/schemas/tasks.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
/**
 * Tool input schemas for the automations app. Imported by both the
 * in-process source (`src/platform/tasks/source.ts`) and the tool
 * handlers beside it (`src/platform/tasks/server.ts`) so the two
 * consumers always agree on the wire shape.
 *
 * Shape convention (per src/platform/AGENTS.md §1.3):
 *
 *   create: { manifest: { ...config }, body: <prompt> }
 *   update: { name, manifest?: Partial<config>, body?: <new prompt> }
 *
 * `manifest` is the persistent automation definition; `body` is the prompt
 * that opens each run — the analog of a skill's markdown
 * body. The operator-only field `source` is intentionally absent from the
 * LLM-facing schema; it lives on the stored type and is set by the runtime,
 * never by an authoring caller.
 */
import { type Static } from "@sinclair/typebox";
import { NotificationRouteMatch } from "./notifications.ts";
export declare const AutomationsCreateInput: import("@sinclair/typebox").TObject<{
    manifest: import("@sinclair/typebox").TObject<{
        name: import("@sinclair/typebox").TString;
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        schedule: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            type: import("@sinclair/typebox").TUnsafe<"cron" | "interval" | "event" | "once">;
            expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            at: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            match: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
            }>>;
            debounceMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            maxFiresPerHour: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        }>>;
        enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
        }>>;
        inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
        outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
        kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"saved" | "oneoff">>;
    }>;
    body: import("@sinclair/typebox").TString;
}>;
export type AutomationsCreateInput = Static<typeof AutomationsCreateInput>;
export declare const AutomationsUpdateInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
    manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        schedule: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
            type: import("@sinclair/typebox").TUnsafe<"cron" | "interval" | "event" | "once">;
            expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            at: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            match: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
            }>>;
            debounceMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            maxFiresPerHour: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        }>, import("@sinclair/typebox").TNull]>>;
        enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
        }>>;
        inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<Record<string, unknown>>, import("@sinclair/typebox").TNull]>>;
        outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<Record<string, unknown>>, import("@sinclair/typebox").TNull]>>;
    }>>;
    body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type AutomationsUpdateInput = Static<typeof AutomationsUpdateInput>;
export declare const AutomationsDeleteInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;
export type AutomationsDeleteInput = Static<typeof AutomationsDeleteInput>;
export declare const AutomationsListInput: import("@sinclair/typebox").TObject<{
    enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
    source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"user" | "agent">>;
    kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"all" | "saved" | "oneoff">>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    cursor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type AutomationsListInput = Static<typeof AutomationsListInput>;
export declare const AutomationsStatusInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type AutomationsStatusInput = Static<typeof AutomationsStatusInput>;
export declare const AutomationsRunsInput: import("@sinclair/typebox").TObject<{
    automationId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"skipped" | "running" | "success" | "degraded" | "failure" | "timeout" | "cancelled">>;
    since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    before: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type AutomationsRunsInput = Static<typeof AutomationsRunsInput>;
export declare const AutomationsRunInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    input: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<unknown>>;
    idempotencyKey: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    prompt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
    outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
    allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
    limits: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    }>>;
    budget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
    }>>;
}>;
export type AutomationsRunInput = Static<typeof AutomationsRunInput>;
export declare const AutomationsCancelInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString;
}>;
export type AutomationsCancelInput = Static<typeof AutomationsCancelInput>;
export declare const AutomationsRunResultInput: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    runId: import("@sinclair/typebox").TString;
}>;
export type AutomationsRunResultInput = Static<typeof AutomationsRunResultInput>;
/**
 * Status of the most recent automation run, as exposed via the list/
 * summary surface. Mirrors `AutomationRun["status"]` minus `"running"`
 * — the list view shows the most recent COMPLETED run's outcome, never
 * one in flight.
 */
export type AutomationLastRunStatus = "success" | "degraded" | "failure" | "timeout" | "skipped";
/**
 * Summary row returned per automation by `handleList`. Subset of the
 * stored `Automation` shape plus a couple of human-formatted fields the
 * UI surfaces directly. `lastRunAt` / `nextRunAt` are human-relative
 * strings (e.g. "in 2h", "4h ago") — the raw ISO timestamps stay on the
 * stored `Automation`.
 */
export interface AutomationSummary {
    id: string;
    name: string;
    description?: string;
    /** Human-readable trigger, e.g. "Daily at 8:00 AM HST", "Once at …", "Manual only". */
    schedule: string;
    /** The schedule's type, or `none` when nothing fires it unattended. */
    scheduleType: "cron" | "interval" | "event" | "once" | "none";
    kind: "saved" | "oneoff";
    /** Set when a once schedule has fired or missed its time; the automation is inert until re-armed. */
    onceDone?: AutomationOnceDone;
    enabled: boolean;
    source: "user" | "agent";
    runCount: number;
    lastRunStatus: AutomationLastRunStatus | null;
    lastRunAt: string | null;
    nextRunAt: string | null;
    disabledAt: string | null;
    disabledReason: string | null;
    estimatedCostPerDay: number;
}
export interface AutomationsListOutput {
    automations: AutomationSummary[];
    /** Matches for the given filters BEFORE the page cap — not `automations.length`. */
    total: number;
    /** How many are in this response. */
    returned: number;
    /**
     * Pass as `cursor` to get the next page; `null` when this is the last one.
     *
     * A cursor rather than a numeric offset because the page must stay correct
     * across a mutation between calls: an offset re-slices a list whose earlier
     * entries may have been deleted, which silently skips the records that
     * shifted past the boundary. Anchoring to the last id read means a deletion
     * behind the cursor cannot move the records ahead of it.
     */
    nextCursor: string | null;
    hasMore: boolean;
    /**
     * Present only when the page cap hid matches. Prose rather than a flag alone
     * because the consumer is a model reading the payload: a bare `hasMore: true`
     * has been read as incidental, whereas a sentence naming the missing count is
     * not. Coverage that silently shrinks is worse than an error — the caller
     * concludes "no match found" from a set it never saw.
     */
    truncated?: string;
}
/**
 * Structural mirror of a single AutomationRun record as returned by
 * the handlers. Kept in sync with `AutomationRun` in
 * `platform/tasks/types.ts` via the assertion test referenced
 * above. New fields added there MUST also appear here.
 */
export interface AutomationRunRecord {
    id: string;
    automationId: string;
    startedAt: string;
    completedAt?: string;
    status: "queued" | "running" | "success" | "degraded" | "failure" | "timeout" | "cancelled" | "skipped";
    inputTokens: number;
    outputTokens: number;
    toolCalls: number;
    iterations: number;
    error?: string;
    transient?: boolean;
    trigger?: "scheduled" | "manual" | "event";
    resultPreview?: string;
    stopReason?: "complete" | "max_iterations" | "max_input_tokens" | "spend_limit" | "length" | "content_filter" | "error" | "other";
    /** The spend account that stopped the run, when `stopReason` is `spend_limit`. */
    spendAccountId?: string;
    /** The JSON input the run was given. */
    input?: unknown;
    /** The idempotency key the run was requested with. */
    idempotencyKey?: string;
    /** Whether the deliverable matched the automation's outputSchema; absent without one. */
    outputSchemaValid?: boolean;
    /** Why the deliverable did not match the outputSchema. */
    outputSchemaErrors?: string[];
}
/**
 * One tool call from a run's activity log. Mirror of `RunToolCall` in
 * `platform/tasks/types.ts` (kept here to avoid a cross-tree import;
 * see the top-of-section note).
 */
export interface RunToolCallRecord {
    id: string;
    name: string;
    input: unknown;
    output: string;
    ok: boolean;
    ms: number;
}
/** A ref to a file a run produced. Mirror of `RunFileRef`. */
export interface RunFileRefRecord {
    id: string;
    filename: string;
}
/**
 * The full deliverable of a run, returned by `handleRunResult`. Mirror of
 * `AutomationRunResult` in `platform/tasks/types.ts`. A run is not a
 * conversation: the result carries the final output, the activity log, and refs
 * to any files the run wrote in the workspace file store.
 */
export interface AutomationsRunResultOutput {
    runId: string;
    automationId: string;
    completedAt: string;
    output: string;
    activityLog: RunToolCallRecord[];
    outputFiles: RunFileRefRecord[];
    usage: {
        inputTokens: number;
        outputTokens: number;
        iterations: number;
    };
    stopReason?: "complete" | "max_iterations" | "max_input_tokens" | "spend_limit" | "length" | "content_filter" | "error" | "other";
    /** The deliverable parsed as JSON, when the automation has an outputSchema and it parsed. */
    structured?: unknown;
}
/**
 * Token budget block on a stored automation. Mirror of the
 * `TokenBudget` interface; kept here to avoid a cross-tree import
 * (see top-of-section comment).
 */
export interface AutomationTokenBudget {
    maxInputTokens?: number;
    maxOutputTokens?: number;
    period?: "daily" | "monthly";
}
/** How a once schedule's occurrence ended, and when. Mirror of `OnceDone`. */
export interface AutomationOnceDone {
    at: string;
    outcome: "ran" | "missed";
}
/**
 * Schedule spec block on a stored automation. Mirror of `ScheduleSpec`.
 */
export interface AutomationScheduleSpec {
    type: "cron" | "interval" | "event" | "once";
    expression?: string;
    timezone?: string;
    at?: string;
    intervalMs?: number;
    match?: NotificationRouteMatch;
    debounceMs?: number;
    maxFiresPerHour?: number;
}
/**
 * Automation detail returned by `handleStatus`. Spreads the stored
 * Automation and overlays a few computed fields the UI consumes
 * directly: humanized schedule + relative-time strings, cost numbers,
 * and undefined→null coercion on optional fields (`tokenBudget`,
 * `budgetResetAt`) so JSON consumers see a consistent shape per field.
 */
export interface AutomationStatusDetail {
    id: string;
    name: string;
    description?: string;
    prompt: string;
    schedule?: AutomationScheduleSpec;
    kind?: "saved" | "oneoff";
    onceDone?: AutomationOnceDone;
    scheduleHuman: string;
    enabled: boolean;
    source: "user" | "agent";
    ownerId?: string;
    workspaceId?: string;
    model?: string | null;
    skill?: string;
    allowedTools?: string[];
    inputSchema?: Record<string, unknown>;
    outputSchema?: Record<string, unknown>;
    maxIterations?: number;
    maxInputTokens?: number;
    maxRunDurationMs?: number;
    runCount: number;
    consecutiveErrors: number;
    cumulativeInputTokens: number;
    cumulativeOutputTokens: number;
    tokenBudget: AutomationTokenBudget | null;
    budgetResetAt: string | null;
    lastRunAt?: string;
    lastRunAtHuman: string | null;
    lastRunStatus?: AutomationLastRunStatus;
    nextRunAt?: string;
    nextRunAtHuman: string | null;
    disabledAt?: string;
    disabledReason?: string;
    createdAt: string;
    updatedAt: string;
    actualCostUsd: number;
    estimatedCostPerRun: number;
    estimatedCostPerDay: number;
    estimatedCostPerMonth: number;
}
export interface AutomationsStatusOutput {
    automation: AutomationStatusDetail;
    recentRuns: AutomationRunRecord[];
}
export interface AutomationsRunsOutput {
    runs: AutomationRunRecord[];
    total: number;
    /**
     * Pass as `before` for the next older page of one automation's history;
     * absent when nothing older remains (or when runs span every automation).
     */
    nextBefore?: string;
}
/**
 * Discriminated union — `handleRun` returns one of two shapes:
 *
 *   { run: AutomationRunRecord; enabled; message? }  when the run finishes
 *                                                    inside the sync-wait
 *                                                    window (~30s default).
 *
 *   { status: "dispatched"; automationId;            when the run is still
 *     startedAt; enabled; message }                  in flight after the
 *                                                    window. It keeps going;
 *                                                    its record lands in
 *                                                    `tasks__runs`
 *                                                    (`since: startedAt`)
 *                                                    when it ends.
 *
 *   { status: "queued"; automationId; position;     when every run slot was
 *     queuedAt; enabled; message }                   busy. It starts as soon
 *                                                    as a slot frees; its record
 *                                                    lands in `tasks__runs`
 *                                                    (`since: queuedAt`) when it
 *                                                    ends. `tasks__cancel`
 *                                                    removes it from the queue.
 *
 * A Run now the scheduler refuses (already running or queued, a full queue, a
 * spent token budget) returns the first shape with a `skipped` run whose
 * `error` says why.
 *
 * `enabled` is the automation's own flag. Run now runs a disabled automation,
 * because it is a deliberate act and the create form's test run depends on
 * it; a disabled automation is not fired by its schedule or by events, and
 * `message` says so.
 *
 * Both shapes indicate the dispatch succeeded; only an error response
 * indicates failure to dispatch. Consumers MUST narrow before
 * dereferencing `run.*` — `as { run: ... }` is the anti-pattern that
 * caused the production CLI crash this type prevents.
 */
export type AutomationsRunOutput = {
    run: AutomationRunRecord;
    enabled: boolean;
    message?: string;
} | {
    status: "dispatched";
    automationId: string;
    /** The run's id: read its result with tasks__run_result. */
    runId: string;
    startedAt: string;
    enabled: boolean;
    message: string;
} | {
    status: "queued";
    automationId: string;
    /** The run's id: read its result with tasks__run_result. */
    runId: string;
    /** 1 is next to start. */
    position: number;
    queuedAt: string;
    enabled: boolean;
    message: string;
};
export interface AutomationsCancelOutput {
    cancelled: boolean;
    id: string;
    message: string;
}
/**
 * A stored automation, as `tasks__create` and `tasks__update`
 * return it. Mirror of `Automation` (`src/platform/tasks/types.ts`),
 * held to it by `src/platform/tasks/output-types-drift-guard.ts`.
 */
export interface AutomationRecord {
    id: string;
    name: string;
    description?: string;
    prompt: string;
    schedule?: AutomationScheduleSpec;
    kind?: "saved" | "oneoff";
    onceDone?: AutomationOnceDone;
    skill?: string;
    allowedTools?: string[];
    inputSchema?: Record<string, unknown>;
    outputSchema?: Record<string, unknown>;
    maxIterations?: number;
    maxInputTokens?: number;
    maxRunDurationMs?: number;
    model?: string | null;
    enabled: boolean;
    ownerId?: string;
    workspaceId?: string;
    source: "user" | "agent";
    createdAt: string;
    updatedAt: string;
    lastRunAt?: string;
    lastRunStatus?: AutomationLastRunStatus;
    nextRunAt?: string;
    runCount: number;
    consecutiveErrors: number;
    disabledAt?: string;
    disabledReason?: string;
    cumulativeInputTokens: number;
    cumulativeOutputTokens: number;
    tokenBudget?: AutomationTokenBudget;
    budgetResetAt?: string;
}
/**
 * The caps a run of the automation executes under: each cap the definition
 * sets, lowered to the runtime's per-run ceiling, and the runtime default held
 * to the ceiling where it sets none. `maxInputTokens` is absent when the run
 * has no input-token cap (neither the definition nor the runtime sets one).
 * `message` names any cap that was lowered.
 */
export interface AutomationEffectiveLimits {
    maxIterations: number;
    maxInputTokens?: number;
    maxRunDurationMs: number;
}
export interface AutomationsCreateOutput {
    automation: AutomationRecord;
    created: boolean;
    message: string;
    effectiveLimits: AutomationEffectiveLimits;
}
export interface AutomationsUpdateOutput {
    automation: AutomationRecord;
    updated: boolean;
    message: string;
    effectiveLimits: AutomationEffectiveLimits;
}
export interface AutomationsDeleteOutput {
    deleted: boolean;
    id: string;
    message: string;
}
