/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/platform/schemas/tasks.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
/**
 * Tool input schemas for the tasks app. Imported by both the
 * in-process source (`src/platform/tasks/source.ts`) and the tool
 * handlers beside it (`src/platform/tasks/server.ts`) so the two
 * consumers always agree on the wire shape.
 *
 * Shape convention (per src/platform/AGENTS.md §1.3):
 *
 *   create: { manifest: { ...config }, body: <prompt> }
 *   update: { taskId, manifest?: patch of config (null clears), body?: <new prompt> }
 *   run / run_batch inline: { definition: { manifest?, body? } }
 *
 * One definition shape: `manifest` carries the stored task's field names and
 * `body` is the prompt that opens each run, in create, update, and an inline
 * one-off alike. Every tool names a task by `taskId` and a run by `runId`. The
 * operator-only field `source` is intentionally absent from the LLM-facing
 * schema; it lives on the stored type and is set by the runtime.
 *
 * Numeric bounds here are literals that mirror the constants the handlers
 * enforce (`src/limits.ts`, `src/platform/tasks/types.ts`): this tree is
 * codegen'd under a strict rootDir (`scripts/tsconfig.codegen-web.json`) that
 * forbids importing from outside `src/platform/schemas/`.
 */
import { type Static } from "@sinclair/typebox";
import { NotificationRouteMatch } from "./notifications.ts";
export declare const TasksCreateInput: import("@sinclair/typebox").TObject<{
    manifest: import("@sinclair/typebox").TObject<{
        skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
        }>>;
        inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
        outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
        criteria: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TString;
            rule: import("@sinclair/typebox").TString;
            type: import("@sinclair/typebox").TUnsafe<"boolean" | "score" | "choice">;
            levels: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            pass: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TBoolean, import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TString, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>]>>;
        }>>>;
        confidenceThreshold: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
        judge: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            server: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
        }>>;
        onPoorResult: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"record" | "notify" | "retry_once">>;
        name: import("@sinclair/typebox").TString;
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        schedule: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            type: import("@sinclair/typebox").TUnsafe<"cron" | "interval" | "event" | "once">;
            expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            at: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            match: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
            }>>;
            debounceMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxFiresPerHour: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        }>>;
        enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"saved" | "oneoff">>;
    }>;
    body: import("@sinclair/typebox").TString;
}>;
export type TasksCreateInput = Static<typeof TasksCreateInput>;
export declare const TasksUpdateInput: import("@sinclair/typebox").TObject<{
    taskId: import("@sinclair/typebox").TString;
    manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TNull]>>;
        schedule: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
            type: import("@sinclair/typebox").TUnsafe<"cron" | "interval" | "event" | "once">;
            expression: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            timezone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            at: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            intervalMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            match: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
            }>>;
            debounceMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxFiresPerHour: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
        }>, import("@sinclair/typebox").TNull]>>;
        enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
        skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TNull]>>;
        model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TString, import("@sinclair/typebox").TNull]>>;
        allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>, import("@sinclair/typebox").TNull]>>;
        maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TNull]>>;
        maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TNull]>>;
        maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TNull]>>;
        tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
        }>, import("@sinclair/typebox").TNull]>>;
        inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<Record<string, unknown>>, import("@sinclair/typebox").TNull]>>;
        outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<Record<string, unknown>>, import("@sinclair/typebox").TNull]>>;
        criteria: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TString;
            rule: import("@sinclair/typebox").TString;
            type: import("@sinclair/typebox").TUnsafe<"boolean" | "score" | "choice">;
            levels: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            pass: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TBoolean, import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TString, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>]>>;
        }>>, import("@sinclair/typebox").TNull]>>;
        confidenceThreshold: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TNumber, import("@sinclair/typebox").TNull]>>;
        judge: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
            server: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
        }>, import("@sinclair/typebox").TNull]>>;
        onPoorResult: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TUnsafe<"record" | "notify" | "retry_once">, import("@sinclair/typebox").TNull]>>;
    }>>;
    body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type TasksUpdateInput = Static<typeof TasksUpdateInput>;
export declare const TasksDeleteInput: import("@sinclair/typebox").TObject<{
    taskId: import("@sinclair/typebox").TString;
}>;
export type TasksDeleteInput = Static<typeof TasksDeleteInput>;
export declare const TasksListInput: import("@sinclair/typebox").TObject<{
    enabled: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
    source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"user" | "agent">>;
    kind: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"all" | "saved" | "oneoff">>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    cursor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type TasksListInput = Static<typeof TasksListInput>;
export declare const TasksStatusInput: import("@sinclair/typebox").TObject<{
    taskId: import("@sinclair/typebox").TString;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
}>;
export type TasksStatusInput = Static<typeof TasksStatusInput>;
export declare const TasksRunsInput: import("@sinclair/typebox").TObject<{
    taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    label: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"Succeeded" | "Poor result" | "Needs review" | "Failed" | "Skipped" | "Cancelled">>;
    verdict: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"pass" | "fail" | "uncertain" | "not_assessed">>;
    since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    before: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    excludeBatchRuns: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
}>;
export type TasksRunsInput = Static<typeof TasksRunsInput>;
export declare const TasksUpcomingInput: import("@sinclair/typebox").TObject<{
    days: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
}>;
export type TasksUpcomingInput = Static<typeof TasksUpcomingInput>;
export declare const TasksStatsInput: import("@sinclair/typebox").TObject<{
    since: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type TasksStatsInput = Static<typeof TasksStatsInput>;
export declare const TasksJudgesInput: import("@sinclair/typebox").TObject<{}>;
export type TasksJudgesInput = Static<typeof TasksJudgesInput>;
export declare const TasksRunInput: import("@sinclair/typebox").TObject<{
    taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    definition: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
            }>>;
            inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
            outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
            criteria: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
                rule: import("@sinclair/typebox").TString;
                type: import("@sinclair/typebox").TUnsafe<"boolean" | "score" | "choice">;
                levels: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                pass: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TBoolean, import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TString, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>]>>;
            }>>>;
            confidenceThreshold: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            judge: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                server: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
            }>>;
            onPoorResult: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"record" | "notify" | "retry_once">>;
        }>>;
        body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    }>>;
    input: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<unknown>>;
    idempotencyKey: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type TasksRunInput = Static<typeof TasksRunInput>;
export declare const TasksAssessInput: import("@sinclair/typebox").TObject<{
    runId: import("@sinclair/typebox").TString;
    taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    verdict: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"pass" | "fail">>;
    note: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    reassess: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
}>;
export type TasksAssessInput = Static<typeof TasksAssessInput>;
export declare const TasksCancelInput: import("@sinclair/typebox").TObject<{
    runId: import("@sinclair/typebox").TString;
}>;
export type TasksCancelInput = Static<typeof TasksCancelInput>;
export declare const TasksRunResultInput: import("@sinclair/typebox").TObject<{
    runId: import("@sinclair/typebox").TString;
    taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type TasksRunResultInput = Static<typeof TasksRunResultInput>;
export declare const TasksRunBatchInput: import("@sinclair/typebox").TObject<{
    taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    definition: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        manifest: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            skill: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            model: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            allowedTools: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
            maxIterations: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            maxRunDurationMs: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
            tokenBudget: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                maxInputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                maxOutputTokens: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
                period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"daily" | "monthly">>;
            }>>;
            inputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
            outputSchema: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
            criteria: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
                id: import("@sinclair/typebox").TString;
                rule: import("@sinclair/typebox").TString;
                type: import("@sinclair/typebox").TUnsafe<"boolean" | "score" | "choice">;
                levels: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
                pass: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TBoolean, import("@sinclair/typebox").TInteger, import("@sinclair/typebox").TString, import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>]>>;
            }>>>;
            confidenceThreshold: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
            judge: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
                server: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
                options: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
            }>>;
        }>>;
        body: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    }>>;
    items: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnsafe<unknown>>;
    concurrency: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    budgetUsd: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    stopWhen: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        minPassRate: import("@sinclair/typebox").TNumber;
        afterItems: import("@sinclair/typebox").TInteger;
    }>>;
    idempotencyKey: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type TasksRunBatchInput = Static<typeof TasksRunBatchInput>;
export declare const TasksBatchInput: import("@sinclair/typebox").TObject<{
    batchId: import("@sinclair/typebox").TString;
    results: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
    filter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"pending" | "skipped" | "failed" | "pass" | "fail" | "uncertain" | "not_assessed" | "cancelled" | "failing">>;
    cursor: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
}>;
export type TasksBatchInput = Static<typeof TasksBatchInput>;
export declare const TasksBatchControlInput: import("@sinclair/typebox").TObject<{
    batchId: import("@sinclair/typebox").TString;
    action: import("@sinclair/typebox").TUnsafe<"pause" | "resume" | "cancel" | "rerun_failed">;
    budgetUsd: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type TasksBatchControlInput = Static<typeof TasksBatchControlInput>;
export declare const TasksBatchesInput: import("@sinclair/typebox").TObject<{
    taskId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    state: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"cancelled" | "running" | "paused" | "completed">>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TInteger>;
}>;
export type TasksBatchesInput = Static<typeof TasksBatchesInput>;
/**
 * Status of the most recent task run, as exposed via the list/
 * summary surface. Mirrors `TaskRun["status"]` minus `"running"`
 * — the list view shows the most recent COMPLETED run's outcome, never
 * one in flight.
 */
export type TaskLastRunStatus = "success" | "degraded" | "failure" | "timeout" | "skipped";
/**
 * Summary row returned per task by `handleList`. Subset of the stored `Task`
 * shape plus the schedule in words. Times are ISO-8601.
 */
export interface TaskSummary {
    id: string;
    name: string;
    description?: string;
    /** Human-readable trigger, e.g. "Weekdays at 8:00 AM HST", "Once at …", "Manual only". */
    schedule: string;
    /** The schedule's type, or `none` when nothing fires it unattended. */
    scheduleType: "cron" | "interval" | "event" | "once" | "none";
    kind: "saved" | "oneoff";
    /** Set when a once schedule has fired or missed its time; the task is inert until re-armed. */
    onceDone?: TaskOnceDone;
    enabled: boolean;
    source: "user" | "agent";
    runCount: number;
    lastRunStatus: TaskLastRunStatus | null;
    lastRunAt: string | null;
    /** When its schedule next fires; null when nothing will (no timed schedule, or disabled). */
    nextRunAt: string | null;
    disabledAt: string | null;
    disabledReason: string | null;
    estimatedCostPerDay: number;
    /** The task's input schema, when it has one: a caller can ask for the input before it runs. */
    inputSchema?: Record<string, unknown>;
}
export interface TasksListOutput {
    tasks: TaskSummary[];
    /** Matches for the given filters BEFORE the page cap — not `tasks.length`. */
    total: number;
    /** How many are in this response. */
    returned: number;
    /**
     * Pass as `cursor` to get the next page; `null` when this is the last one.
     *
     * A cursor rather than a numeric offset because the page must stay correct
     * across a mutation between calls: an offset re-slices a list whose earlier
     * entries may have been deleted, which silently skips the records that
     * shifted past the boundary. Anchoring to the last id read means a deletion
     * behind the cursor cannot move the records ahead of it.
     */
    nextCursor: string | null;
    hasMore: boolean;
    /**
     * Present only when the page cap hid matches. Prose rather than a flag alone
     * because the consumer is a model reading the payload: a bare `hasMore: true`
     * has been read as incidental, whereas a sentence naming the missing count is
     * not. Coverage that silently shrinks is worse than an error — the caller
     * concludes "no match found" from a set it never saw.
     */
    truncated?: string;
}
/** One acceptance criterion. Mirror of `Criterion`. */
export interface TaskCriterion {
    id: string;
    rule: string;
    type: "boolean" | "score" | "choice";
    levels?: string[];
    options?: string[];
    pass?: boolean | number | string | string[];
}
/** Which judge answers a task's criteria. Mirror of `TaskJudge`. */
export interface TaskJudgeSpec {
    server?: string;
    id?: string;
    options?: Record<string, unknown>;
}
/** One criterion as judged and decided. Mirror of `CriterionResult`. */
export interface TaskCriterionResult {
    id: string;
    answer: boolean | number | string;
    passed: boolean;
    confidence: number;
    probabilities?: Record<string, number>;
    rationale?: string;
}
/** A person's verdict on a run. Mirror of `HumanVerdict`. */
export interface TaskHumanVerdict {
    verdict: "pass" | "fail";
    note?: string;
    by: string;
    via: "ui" | "remote";
    at: string;
}
/** Whether a run's deliverable is acceptable. Mirror of `RunAssessment`. */
export interface TaskRunAssessment {
    verdict: "pass" | "fail" | "uncertain" | "not_assessed";
    reason?: {
        code: string;
        message: string;
    };
    schema?: {
        valid: boolean;
        errors?: string[];
    };
    criteria?: TaskCriterionResult[];
    judge?: {
        server: string;
        id: string;
        version?: string;
        calibrated: boolean;
    };
    usage?: {
        inputTokens?: number;
        outputTokens?: number;
        costUsd?: number;
    };
    stateTruncated?: boolean;
    assessedAt: string;
    human?: TaskHumanVerdict;
}
/** How a run ended (ADR-0045), derived from its record. Mirror of `RunExecution`. */
export type TaskRunExecution = "queued" | "running" | "skipped" | "completed" | "incomplete" | "failed" | "cancelled";
/** The one label a run reads as, derived and never stored. Mirror of `RunLabel`. */
export type TaskRunLabel = "Succeeded" | "Poor result" | "Needs review" | "Failed" | "Skipped" | "Cancelled" | "Queued" | "Running";
/**
 * Structural mirror of a single TaskRun record as returned by
 * the handlers. Kept in sync with `TaskRun` in
 * `platform/tasks/types.ts` via the assertion test referenced
 * above. New fields added there MUST also appear here.
 */
export interface TaskRunRecord {
    id: string;
    taskId: string;
    startedAt: string;
    completedAt?: string;
    status: "queued" | "running" | "success" | "degraded" | "failure" | "timeout" | "cancelled" | "skipped";
    inputTokens: number;
    outputTokens: number;
    toolCalls: number;
    iterations: number;
    error?: string;
    transient?: boolean;
    trigger?: "scheduled" | "manual" | "event";
    resultPreview?: string;
    stopReason?: "complete" | "max_iterations" | "max_input_tokens" | "spend_limit" | "length" | "content_filter" | "error" | "other";
    /** The spend account that stopped the run, when `stopReason` is `spend_limit`. */
    spendAccountId?: string;
    /** The JSON input the run was given. */
    input?: unknown;
    /** The idempotency key the run was requested with. */
    idempotencyKey?: string;
    /** Whether the deliverable matched the task's outputSchema; absent without one. */
    outputSchemaValid?: boolean;
    /** Why the deliverable did not match the outputSchema. */
    outputSchemaErrors?: string[];
    /** Tools whose failed calls no later call made good. */
    unrecoveredToolFailures?: string[];
    /** Whether the deliverable is acceptable; absent until assessed. */
    assessment?: TaskRunAssessment;
    /** The run this one retries. */
    retryOf?: string;
    /** The batch this run is an item of. */
    batchId?: string;
    /** The item's index in its batch. */
    batchIndex?: number;
    /** What the run's model calls cost, in USD. */
    costUsd?: number;
}
/**
 * A run record as the run surfaces return it (`tasks__runs`,
 * `tasks__status`, `tasks__run`, `tasks__assess`): the stored record plus
 * its derived execution and label, which are computed on read and never
 * stored.
 */
export type TaskRunView = TaskRunRecord & {
    execution: TaskRunExecution;
    label: TaskRunLabel;
};
/**
 * One tool call from a run's activity log. Mirror of `RunToolCall` in
 * `platform/tasks/types.ts` (kept here to avoid a cross-tree import;
 * see the top-of-section note).
 */
export interface RunToolCallRecord {
    id: string;
    name: string;
    input: unknown;
    output: string;
    ok: boolean;
    ms: number;
}
/** A ref to a file a run produced. Mirror of `RunFileRef`. */
export interface RunFileRefRecord {
    id: string;
    filename: string;
}
/**
 * A run's full deliverable: the untruncated final output, the activity log,
 * and refs to any files the run wrote in the workspace file store. Mirror of
 * `TaskRunResult` in `platform/tasks/types.ts`, less the ids the run record
 * beside it carries. A run is not a conversation.
 */
export interface TaskRunResultBody {
    completedAt: string;
    output: string;
    activityLog: RunToolCallRecord[];
    outputFiles: RunFileRefRecord[];
    usage: {
        inputTokens: number;
        outputTokens: number;
        iterations: number;
    };
    stopReason?: "complete" | "max_iterations" | "max_input_tokens" | "spend_limit" | "length" | "content_filter" | "error" | "other";
    /** The deliverable parsed as JSON, when the task has an outputSchema and it parsed. */
    structured?: unknown;
    /** Why the run failed or did not start, as its record says. */
    error?: string;
}
/**
 * `tasks__run_result`: one run by id, whatever state it is in. `status` says
 * whether it has ended; a run still queued or running is an answer, not an
 * error, so a caller polls by calling again.
 */
export type TasksRunResultOutput = {
    status: "queued" | "running";
    run: TaskRunView;
    /** Queued only: 1 is next to start. */
    position?: number;
    message: string;
} | {
    status: "ended";
    run: TaskRunView;
    /**
     * Every recorded run has one: a run that failed before the engine
     * returned, or never started, has an empty output and activity log and
     * its `error`. Absent only for a run recorded before every run wrote one.
     */
    result?: TaskRunResultBody;
};
/**
 * Token budget block on a stored task. Mirror of the
 * `TokenBudget` interface; kept here to avoid a cross-tree import
 * (see top-of-section comment).
 */
export interface TaskTokenBudget {
    maxInputTokens?: number;
    maxOutputTokens?: number;
    period?: "daily" | "monthly";
}
/** How a once schedule's occurrence ended, and when. Mirror of `OnceDone`. */
export interface TaskOnceDone {
    at: string;
    outcome: "ran" | "missed";
}
/**
 * Schedule spec block on a stored task. Mirror of `ScheduleSpec`.
 */
export interface TaskScheduleSpec {
    type: "cron" | "interval" | "event" | "once";
    expression?: string;
    timezone?: string;
    at?: string;
    intervalMs?: number;
    match?: NotificationRouteMatch;
    debounceMs?: number;
    maxFiresPerHour?: number;
}
/**
 * Task detail returned by `handleStatus`. Spreads the stored
 * Task and overlays a few computed fields the UI consumes
 * directly: humanized schedule + relative-time strings, cost numbers,
 * and undefined→null coercion on optional fields (`tokenBudget`,
 * `budgetResetAt`) so JSON consumers see a consistent shape per field.
 */
export interface TaskStatusDetail {
    id: string;
    name: string;
    description?: string;
    prompt: string;
    schedule?: TaskScheduleSpec;
    kind?: "saved" | "oneoff";
    onceDone?: TaskOnceDone;
    scheduleHuman: string;
    /** The IANA timezone its schedule is read in: the schedule's own, else this instance's. */
    timezone: string;
    enabled: boolean;
    source: "user" | "agent";
    ownerId?: string;
    workspaceId?: string;
    model?: string | null;
    skill?: string;
    allowedTools?: string[];
    inputSchema?: Record<string, unknown>;
    outputSchema?: Record<string, unknown>;
    criteria?: TaskCriterion[];
    confidenceThreshold?: number;
    judge?: TaskJudgeSpec;
    onPoorResult?: "record" | "notify" | "retry_once";
    maxIterations?: number;
    maxInputTokens?: number;
    maxRunDurationMs?: number;
    runCount: number;
    consecutiveErrors: number;
    cumulativeInputTokens: number;
    cumulativeOutputTokens: number;
    tokenBudget: TaskTokenBudget | null;
    budgetResetAt: string | null;
    lastRunAt?: string;
    lastRunStatus?: TaskLastRunStatus;
    nextRunAt?: string;
    disabledAt?: string;
    disabledReason?: string;
    createdAt: string;
    updatedAt: string;
    estimatedCostPerRun: number;
    estimatedCostPerDay: number;
    estimatedCostPerMonth: number;
}
export interface TasksStatusOutput {
    task: TaskStatusDetail;
    recentRuns: TaskRunView[];
}
export interface TasksRunsOutput {
    runs: TaskRunView[];
    total: number;
    /**
     * Pass as `before` for the next older page, of one task's history or of
     * every task's; absent when nothing older remains. A first page read without
     * `before` reads only the hot indexes, so across every task it reports more
     * only when the hot indexes hold more.
     */
    nextBefore?: string;
}
/**
 * A warning a write returns about the task it saved, which it saved anyway.
 * `allowed_tool_unavailable`: one allowedTools entry matches no tool the owner
 * can reach in this workspace; a run will fail until that changes.
 * `no_judge`, `judge_ambiguous`, `judge_not_found`: the task has criteria and
 * its workspace has no judge server it can use (none connected, several and
 * none named, or the named one is not a connected judge), so its runs are
 * `uncertain` (Needs review) until one is connected or named.
 */
export interface TaskWarning {
    code: "no_judge" | "judge_ambiguous" | "judge_not_found" | "allowed_tool_unavailable";
    message: string;
}
/**
 * `handleRun` returns one of three shapes:
 *
 *   { run; enabled; message? }               the run ended inside the
 *                                            sync-wait window (~30s), or was
 *                                            refused before it started: a
 *                                            `skipped` run whose `error` says
 *                                            why (already running or queued,
 *                                            a full queue, a spent budget).
 *
 *   { status: "dispatched"; runId; ... }     still running after the window;
 *                                            it keeps going.
 *
 *   { status: "queued"; runId; position }    every run slot was busy; it
 *                                            starts as soon as one frees.
 *
 * Read the last two with `tasks__run_result` (runId) until it says `ended`;
 * `tasks__cancel` (runId) stops them. Only an error response means nothing
 * was asked for (an unknown task, bad input, a bad definition).
 *
 * `enabled` is the task's own flag. Run now runs a disabled task, because it
 * is a deliberate act and the create form's test run depends on it; a
 * disabled task is not fired by its schedule or by events, and `message`
 * says so.
 *
 * Consumers MUST narrow before dereferencing `run.*` (`"run" in out`), never
 * `as { run: ... }`.
 */
export type TasksRunOutput = {
    run: TaskRunView;
    enabled: boolean;
    message?: string;
    warnings?: TaskWarning[];
} | {
    status: "dispatched";
    taskId: string;
    /** The run's id: read its result with tasks__run_result. */
    runId: string;
    startedAt: string;
    enabled: boolean;
    message: string;
    warnings?: TaskWarning[];
} | {
    status: "queued";
    taskId: string;
    /** The run's id: read its result with tasks__run_result. */
    runId: string;
    /** 1 is next to start. */
    position: number;
    queuedAt: string;
    enabled: boolean;
    message: string;
    warnings?: TaskWarning[];
};
/** `tasks__assess`: the run's record with its new assessment, as it now reads. */
export interface TasksAssessOutput {
    run: TaskRunView;
    message: string;
}
export interface TasksCancelOutput {
    cancelled: boolean;
    runId: string;
    /** The run's task, when the run was found. */
    taskId?: string;
    message: string;
}
/**
 * A stored task, as `tasks__create` and `tasks__update`
 * return it. Mirror of `Task` (`src/platform/tasks/types.ts`),
 * held to it by `src/platform/tasks/output-types-drift-guard.ts`.
 */
export interface TaskRecord {
    id: string;
    name: string;
    description?: string;
    prompt: string;
    schedule?: TaskScheduleSpec;
    kind?: "saved" | "oneoff";
    onceDone?: TaskOnceDone;
    skill?: string;
    allowedTools?: string[];
    inputSchema?: Record<string, unknown>;
    outputSchema?: Record<string, unknown>;
    criteria?: TaskCriterion[];
    confidenceThreshold?: number;
    judge?: TaskJudgeSpec;
    onPoorResult?: "record" | "notify" | "retry_once";
    maxIterations?: number;
    maxInputTokens?: number;
    maxRunDurationMs?: number;
    model?: string | null;
    enabled: boolean;
    ownerId?: string;
    workspaceId?: string;
    source: "user" | "agent";
    createdAt: string;
    updatedAt: string;
    lastRunAt?: string;
    lastRunStatus?: TaskLastRunStatus;
    nextRunAt?: string;
    runCount: number;
    consecutiveErrors: number;
    disabledAt?: string;
    disabledReason?: string;
    cumulativeInputTokens: number;
    cumulativeOutputTokens: number;
    tokenBudget?: TaskTokenBudget;
    budgetResetAt?: string;
}
/**
 * The caps a run of the task executes under: each cap the definition
 * sets, lowered to the runtime's per-run ceiling, and the runtime default held
 * to the ceiling where it sets none. `maxInputTokens` is absent when the run
 * has no input-token cap (neither the definition nor the runtime sets one).
 * `message` names any cap that was lowered.
 */
export interface TaskEffectiveLimits {
    maxIterations: number;
    maxInputTokens?: number;
    maxRunDurationMs: number;
}
export interface TasksCreateOutput {
    task: TaskRecord;
    message: string;
    effectiveLimits: TaskEffectiveLimits;
    /** The IANA timezone its schedule is read in: the schedule's own, else this instance's. */
    timezone: string;
    /** About the saved task, which was saved anyway. */
    warnings?: TaskWarning[];
}
export interface TasksUpdateOutput {
    task: TaskRecord;
    updated: boolean;
    message: string;
    effectiveLimits: TaskEffectiveLimits;
    /** The IANA timezone its schedule is read in: the schedule's own, else this instance's. */
    timezone: string;
    /** About the saved task, which was saved anyway. */
    warnings?: TaskWarning[];
}
export interface TasksDeleteOutput {
    deleted: boolean;
    id: string;
    message: string;
}
/** How many of a batch's items are in each state. Mirror of `BatchCounts`. */
export interface TaskBatchCounts {
    pending: number;
    queued: number;
    running: number;
    pass: number;
    fail: number;
    uncertain: number;
    not_assessed: number;
    failed: number;
    skipped: number;
    cancelled: number;
}
/** A stored batch. Mirror of `Batch` (`src/platform/tasks/types.ts`). */
export interface TaskBatchRecord {
    id: string;
    taskId: string;
    workspaceId: string;
    ownerId: string;
    items: number;
    concurrency: number;
    budgetUsd?: number;
    stopWhen?: {
        minPassRate: number;
        afterItems: number;
    };
    stopRuleDisarmed?: boolean;
    state: "running" | "paused" | "completed" | "cancelled";
    pause?: {
        reason: "manual" | "budget" | "pass_rate" | "unavailable";
        message: string;
        at: string;
    };
    counts: TaskBatchCounts;
    costUsd: number;
    idempotencyKey?: string;
    createdAt: string;
    updatedAt: string;
    completedAt?: string;
    createdBy: string;
}
/** A batch as the batch tools return it: the record plus figures derived on read. */
export type TaskBatchView = TaskBatchRecord & {
    /** Items with an outcome. */
    done: number;
    /** pass / (pass + fail); null before either. Uncertain is excluded. */
    passRate: number | null;
};
/** One item's result row (`tasks__batch` with `results: true`). */
export interface TaskBatchItemView {
    index: number;
    /** The item's input as JSON, cut to a short preview. */
    inputSummary: string;
    state: "pending" | "queued" | "running" | "done";
    runId?: string;
    previousRunIds?: string[];
    execution?: TaskRunExecution;
    verdict?: "pass" | "fail" | "uncertain" | "not_assessed";
    /** The label the item's run reads as, from its execution and verdict. */
    label?: TaskRunLabel;
    costUsd?: number;
    error?: string;
    /** The top-level scalar fields of the run's structured output, when it has one. */
    output?: Record<string, string | number | boolean | null>;
}
export interface TasksRunBatchOutput {
    batch: TaskBatchView;
    /** True when an earlier call with the same idempotencyKey made this batch. */
    existing: boolean;
    message: string;
    warnings?: TaskWarning[];
}
export interface TasksBatchOutput {
    batch: TaskBatchView;
    /** With `results: true`: one page of items, in index order. */
    results?: TaskBatchItemView[];
    /** Pass as `cursor` for the next page; absent on the last. */
    nextCursor?: number;
}
export interface TasksBatchControlOutput {
    batch: TaskBatchView;
    message: string;
    /** Items the action touched. */
    affected: number;
}
export interface TasksBatchesOutput {
    batches: TaskBatchView[];
}
/** A run that holds a run slot or waits for one (`tasks__upcoming`). */
export interface TaskUpcomingRun {
    taskId: string;
    /** Absent when the task's definition is gone. */
    taskName?: string;
    runId?: string;
    state: "running" | "queued";
    /** Queued only: 1 is next (the numbering of tasks__run's queued answer). */
    position?: number;
    /** Running only. */
    startedAt?: string;
    /** Queued only: when the run was asked for, when it has a ticket. */
    queuedAt?: string;
    trigger?: "scheduled" | "manual" | "event";
    batchId?: string;
    batchIndex?: number;
}
/** One coming fire of a timed schedule. */
export interface TaskUpcomingFire {
    taskId: string;
    taskName: string;
    at: string;
    /** Human-readable schedule. */
    schedule: string;
    scheduleType: "cron" | "interval" | "once";
    /** Past the window: the task's next fire, shown so a rare schedule is not missing. */
    beyondWindow?: boolean;
}
/**
 * A schedule that fires more often than the panel lists one by one: one row
 * with how many times it fires in the window, and its first and last fire.
 */
export interface TaskUpcomingFrequent {
    taskId: string;
    taskName: string;
    schedule: string;
    scheduleType: "cron" | "interval";
    /** Fires within the window; a floor when `countCapped`. */
    count: number;
    /**
     * True when a cron was counted only until it was known to be frequent, so
     * `count` is a floor (shown as "25+"). An interval is always counted exactly.
     */
    countCapped?: boolean;
    first: string;
    /** The last fire in the window; absent when `countCapped`. */
    last?: string;
}
/** A task an event fires, with its fire ceiling and how much of it the last hour used. */
export interface TaskUpcomingEventTask {
    taskId: string;
    taskName: string;
    schedule: string;
    enabled: boolean;
    maxFiresPerHour: number;
    firesLastHour: number;
}
export interface TasksUpcomingOutput {
    running: TaskUpcomingRun[];
    queued: TaskUpcomingRun[];
    /** The window's length in days. */
    days: number;
    /** Where the window ends. */
    windowEnd: string;
    /** Fires within the window, soonest first, then each task's next fire past it. */
    scheduled: TaskUpcomingFire[];
    /** Schedules firing more than the listing threshold in the window, one row each, by first fire. */
    frequent: TaskUpcomingFrequent[];
    events: TaskUpcomingEventTask[];
}
/** One task's runs since a time (`tasks__stats`). */
export interface TaskRunStats {
    taskId: string;
    /** Run records started on or after `since`, batch runs included. */
    runs: number;
    /** Verdicts over those runs; a person's verdict replaces the judge's. */
    pass: number;
    fail: number;
    uncertain: number;
    /** pass / (pass + fail); null when both are 0. */
    passRate: number | null;
    /** What those runs cost, in USD (runs with no recorded cost count 0). */
    costUsd: number;
    /** The newest run, whenever it started. */
    lastRun?: {
        id: string;
        startedAt: string;
        label: TaskRunLabel;
    };
}
export interface TasksStatsOutput {
    since: string;
    tasks: TaskRunStats[];
}
/** The judge servers connected in the workspace (`tasks__judges`). */
export interface TasksJudgesOutput {
    servers: string[];
    /** Why a task naming no judge server would not be judged: none connected, or several. */
    warning?: TaskWarning;
}
