/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source:    src/tools/platform/schemas/usage.ts
 * Generator: scripts/codegen-web-platform-schemas.ts
 *
 * This file is regenerated by `bun run codegen` and verified in CI by
 * `bun run check:codegen`. Manual edits will be overwritten on the
 * next regeneration.
 *
 * To change anything here, edit the source schema and regenerate.
 *
 * AI coding agents: do not propose edits to this file. Edit the source
 * schema at the path above and run `bun run codegen`.
 */
import { type Static } from "@sinclair/typebox";
export declare const UsageReportInput: import("@sinclair/typebox").TObject<{
    period: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"day" | "week" | "month" | "all">>;
    from: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    to: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    groupBy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"model" | "day" | "conversation">>;
}>;
export type UsageReportInput = Static<typeof UsageReportInput>;
