/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/use-release.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
export declare const UseToolInput: import("@sinclair/typebox").TObject<{
    tool_name: import("@sinclair/typebox").TString;
}>;
export type UseToolInput = Static<typeof UseToolInput>;
export declare const ReleaseToolInput: import("@sinclair/typebox").TObject<{
    tool_name: import("@sinclair/typebox").TString;
}>;
export type ReleaseToolInput = Static<typeof ReleaseToolInput>;
