/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/bundles/types.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import type { HookDeclaration } from "../hooks/types.ts";
import type { NotificationsDeclaration } from "../notifications/types.ts";
import type { CredentialRef, CredentialValue } from "../tools/credential-ref.ts";
import type { Connection } from "./connection.ts";
/**
 * Declaration of a UI placement in the shell layout.
 *
 * Sidebar slot convention:
 *   "sidebar" (priority < 10)  → ungrouped core nav (Home, Conversations)
 *   "sidebar" (priority >= 10) → grouped under "general"
 *   "sidebar.<group>"          → named group with label (e.g., "sidebar.apps" → "Apps")
 *   "sidebar.bottom"           → pinned to bottom zone
 *   "main"                     → app route (page content, not a nav item)
 */
export interface PlacementDeclaration {
    /** Which slot this UI fills (e.g., "sidebar", "sidebar.apps", "sidebar.bottom", "main"). */
    slot: string;
    /** ui:// resource URI served by this MCP server. */
    resourceUri: string;
    /** Display priority within the slot (lower = higher). Default: 100. For sidebar: 0-9 = ungrouped core nav, 10+ = grouped. */
    priority?: number;
    /** Human-readable label (for sidebar items, tabs, etc.). */
    label?: string;
    /** Icon (emoji or identifier). */
    icon?: string;
    /** Route path. Registers as /app/<path> (or "/" for Home). Works in sidebar and main slots. */
    route?: string;
    /** Size hint for the slot renderer. */
    size?: "compact" | "full" | "auto";
}
/** Resolved placement entry — PlacementDeclaration + the server it belongs to. */
export interface PlacementEntry extends PlacementDeclaration {
    serverName: string;
    priority: number;
    /** Workspace ID this placement belongs to (undefined = global/protected). */
    wsId?: string;
}
/** UI metadata stored on a bundle entry (from manifest at install time). */
export interface BundleUiMeta {
    name: string;
    icon: string;
    placements?: PlacementDeclaration[];
}
/** Transport configuration for remote MCP servers (url-based bundles). */
export interface RemoteTransportConfig {
    type?: "streamable-http" | "sse";
    auth?: {
        type: "bearer";
        token: CredentialValue;
    } | {
        type: "header";
        name: string;
        value: CredentialValue;
    } | {
        type: "none";
    }
    /**
     * Non-interactive machine-plane auth produced by a named credential
     * PROVIDER (see `src/tools/credential-provider.ts`). The provider name +
     * its `config` are opaque to the kernel. For the `minted` fleet rail they come
     * from the operator-published catalog entry; a brokered connector (Composio)
     * also names a provider, but its URL comes from the vendor's API response, so
     * provider auth alone does NOT imply catalog provenance — see
     * `isMintedFleetSource`. The
     * built-in `"minted"` provider mints a short-lived, workspace-scoped service
     * token against the fleet authorizer (config:
     * `{ audience, scope, tokenUrl?, issuer? }`) and re-mints on expiry. The
     * endpoint resolves via `resolveAuthorizerTokenUrl`: `tokenUrl` is an explicit
     * per-connection endpoint override; `issuer` is the legacy identity from which
     * `${issuer}/token` is derived. Per-connection config wins over the global env.
     * No interactive OAuth, no static secret. The
     * workspace dimension is the connection's own workspace.
     */
     | {
        type: "provider";
        provider: string;
        config: Record<string, unknown>;
    };
    /**
     * Arbitrary outgoing headers. Each value is a literal or a
     * `{ ref: "credential", key }` pointer resolved at the connection's workspace
     * scope, so a vendor that wants its key in a custom header needs no second
     * mechanism.
     */
    headers?: Record<string, CredentialValue>;
    reconnection?: {
        maxReconnectionDelay?: number;
        initialReconnectionDelay?: number;
        maxRetries?: number;
    };
    sessionId?: string;
}
/**
 * One materialized connector-skill overlay bound to a bundle. Recorded on
 * the bundle's `BundleRef.skillsLock` at install so the dedupe path can tell a
 * bundle HAS a curated overlay (skip its `skill://<name>/SKILL.md`), and so the binding
 * is auditable. Cleanup on uninstall is keyed on `serverName` (it removes the
 * whole `connector-skills/<server>/` dir), not on these entries.
 */
export interface ConnectorSkillLockEntry {
    /** Overlay identity used for the lookup (e.g. `gmail`). */
    identity: string;
    /** Pinned overlay-repo version the overlay was fetched at. */
    version: string;
    /** sha256 (hex) of the fetched overlay body — tamper-evidence. */
    sha: string;
    /** Materialized skill file location — recorded for traceability / debugging. */
    path: string;
}
/**
 * Reference to a remote MCP server. One shape: a URL plus the transport,
 * OAuth and skills-lock fields that describe how to reach it and who it
 * speaks as. The runtime connects to servers; it does not acquire, verify,
 * or execute their code, so there is no by-name or by-path variant.
 */
export type BundleRef = {
    url: string;
    /**
     * Canonical reverse-DNS server name from the source `ServerDetail.name`
     * (e.g. `com.stripe/mcp`), slugified. When present, used as the
     * lifecycle / route key directly. When absent (legacy installs),
     * `serverNameFromRef` falls back to `deriveServerName(url)`.
     */
    serverName?: string;
    transport?: RemoteTransportConfig;
    ui?: BundleUiMeta | null;
    /** Materialized connector-skill overlays bound to this bundle. */
    skillsLock?: ConnectorSkillLockEntry[];
    /**
     * OAuth identity scope for this URL bundle. `"workspace"` is the
     * only legal value: one identity per `(workspace, server)`, shared
     * across workspace members. Personal connectors bind to the owning
     * user's personal workspace (`personalWorkspaceIdFor(userId)`).
     */
    oauthScope?: "workspace";
    /**
     * Opt in to the headless authorize-redirect probe. Default false.
     * Set only for bundles whose OAuth provider 302s straight to our
     * callback with a code (Reboot's `Anonymous` dev provider). MUST stay
     * false for normal interactive providers — a server-side `/authorize`
     * probe spins up a vendor auth session bound to our PKCE challenge
     * before the user acts and makes the vendor reject the user's real
     * code (`invalid_code`). See `headlessAuthProbe` in
     * `WorkspaceOAuthProvider`.
     */
    headlessAuthProbe?: boolean;
    /**
     * Pre-registered OAuth client config. Required for vendors that don't
     * support Dynamic Client Registration (RFC 7591) — Gmail, Outlook,
     * HubSpot, Asana, Zoom Marketplace user-OAuth apps. Operator pre-
     * registers an app in the vendor's developer portal, gets back a
     * `client_id` (and usually a `client_secret`), and points this field
     * at it.
     *
     * When present, the OAuth provider skips DCR — `clientInformation()`
     * returns the static client; `saveClientInformation()` is a no-op.
     * `clientSecret` is NEVER inline — it's a reference into the
     * credential store, resolved per-request so the secret doesn't sit
     * in workspace.json. Operators configure the secret in the web UI
     * (the workspace's Connections settings).
     *
     * Omit for vendors that DO support DCR (Granola, Notion). DCR is the
     * default path; static config is the opt-in.
     */
    oauthClient?: OAuthClientConfig;
    /**
     * OAuth scopes the bundle requests. Threaded into the provider's
     * `clientMetadata.scope` so the authorize URL carries the right
     * `scope=` param. Surfaces the requested permissions on the review
     * surface (admin reading workspace.json sees what the bundle asks
     * for) and lets the same MCP server be installed at different
     * permission levels (e.g., Gmail read-only vs. read+send).
     *
     * Omit to use server defaults — correct for DCR servers that derive
     * scopes automatically (Granola, Notion).
     */
    scopes?: string[];
    /**
     * Extra query params appended to the authorize URL. Covers Google's
     * `access_type=offline` + `prompt=consent` (needed for refresh-token
     * issuance) and any vendor-specific parameter. Static strings only —
     * no template interpolation.
     *
     * **Reserved keys rejected at config load** (`client_id`,
     * `redirect_uri`, `response_type`, `state`, `code_challenge`,
     * `code_challenge_method`, `scope`) so config can't override
     * security-critical params the provider sets itself.
     */
    additionalAuthorizationParams?: Record<string, string>;
    /**
     * Set on a **brokered** install — one where a third-party provider
     * (Composio, Smithery) holds the upstream credential and hosts the MCP
     * session. Absent for every runtime-native ref (dcr / static / provider).
     *
     * One block for every provider, deliberately. `provider` names the registered
     * {@link ManagedConnectorProvider} that minted the install, `connectorId` is
     * the catalog entry id it was installed from (every brokered install persists
     * a per-install session URL, so a url→catalog lookup misses and the stamped
     * id is the only way back to the entry), and `providerRef` is
     * `ManagedSession.providerRef` verbatim — opaque provider-scoped coordinates
     * the kernel never reads. Read it through `brokeredRef()`
     * (`./brokered.ts`), which also maps the legacy per-vendor blocks forward.
     */
    brokered?: BrokeredRef;
};
/**
 * The brokered coordinates a `BundleRef` carries — who brokered this install,
 * which catalog entry it came from, and whatever that provider needs to name
 * the thing it minted.
 *
 * `providerRef` is **opaque to the kernel**: it is `ManagedSession.providerRef`
 * as the provider returned it, handed back to that same provider's probe and
 * teardown. Nothing outside `src/connectors/providers/<provider>/` may read a
 * key out of it — the moment the kernel does, the seam carries a schema again
 * and a third provider means teaching the kernel a third shape.
 */
export interface BrokeredRef {
    /** Registered provider id — the connector's brokered `auth` kind. */
    provider: string;
    /** The catalog entry id the install stamped on the ref. */
    connectorId: string;
    /** `ManagedSession.providerRef` verbatim. Opaque here; meaningful only to `provider`. */
    providerRef?: Record<string, string>;
}
/**
 * Config for a pre-registered OAuth client (Track A — alternative to DCR).
 * Lives on the URL bundle ref. The provider reads `clientId` directly
 * and resolves `clientSecret` per-request via `CredentialStore` (the
 * value is never inline in `workspace.json`).
 */
export interface OAuthClientConfig {
    /** OAuth `client_id` from the vendor's developer portal. */
    clientId: string;
    /**
     * Reference to the client secret in the workspace credential store.
     * Configured in the web UI (the workspace's Connections settings).
     * Omit for public PKCE-only clients (rare for pre-registered).
     */
    clientSecret?: CredentialRef;
    /**
     * Token endpoint auth method. Defaults to "none" (PKCE-only public
     * client) when `clientSecret` is absent; "client_secret_post" is the
     * common case when a secret is present. "client_secret_basic" is
     * supported for vendors that mandate it.
     */
    tokenEndpointAuthMethod?: "none" | "client_secret_post" | "client_secret_basic";
}
/** Bundle lifecycle states. */
export type BundleState = "starting" | "running" | "crashed" | "dead" | "stopped"
/**
 * URL bundle is installed but no tokens exist for this principal. Initial
 * state for a freshly-installed URL bundle, and the resting state after
 * `disconnect`. UI shows "Connect" — clicking initiates the OAuth flow
 * (transitioning to `pending_auth`).
 */
 | "not_authenticated"
/**
 * URL bundle is actively in an OAuth flow. The user (or agent) clicked
 * Connect; we've captured an authorization URL and are awaiting the
 * browser callback. Tools are unavailable until the callback completes
 * (transitions to `running`) or fails (transitions to `dead`).
 */
 | "pending_auth"
/**
 * URL bundle was previously `running` but its refresh token failed (rotated,
 * revoked, or AS rejected). Tools that need this connection will fail until
 * the user reconnects. UI shows "Reconnect" — clicking initiates a fresh
 * OAuth flow (transitioning to `pending_auth`).
 *
 * Distinct from `not_authenticated` so the UI can surface a stronger
 * affordance ("your previously-working connection broke") and from
 * `dead` so the UI knows reconnection is the recovery path.
 */
 | "reauth_required";
/** Host manifest metadata at _meta["ai.nimblebrain/host"]. */
export interface HostManifestMeta {
    host_version: "1.0" | "1.1" | "1.2" | "1.3";
    name?: string;
    icon?: string;
    /**
     * RESERVED — not consumed by the host (grouping/briefing prioritization is
     * not wired to it). Tolerated for back-compat; slated for removal (nimblebrain#503).
     */
    category?: string;
    placements?: PlacementDeclaration[];
    primaryView?: {
        resourceUri: string;
    };
    briefing?: BriefingBlock;
    /**
     * Inbound event streams this server accepts, one per vendor. The runtime
     * mints a capability URL per `(workspace, connector, vendor)` at install and
     * hands it to the declared `register_tool`; deliveries to that URL are
     * forwarded verbatim to the declared `route` on this same server.
     *
     * This is the ENTIRE vendor-specific configuration the runtime ever holds —
     * a name, a route, a tool, and prose. Nothing here describes a payload shape
     * or an event taxonomy, and nothing ever should: the moment it does, the
     * runtime has started knowing what a vendor body means, which is the one
     * thing this door exists not to do. See `src/hooks/types.ts`.
     */
    hooks?: HookDeclaration[];
    /**
     * The outbox this server exposes: one MCP resource the runtime reads on a
     * schedule for facts nobody asked for. Belongs to `host_version: "1.3"`.
     *
     * Unlike {@link hooks}, declaring one grants no privilege. A hook
     * declaration decides where this runtime sends a delivery with a freshly
     * minted platform token attached, which is why it is read only from
     * operator-published metadata; an outbox declaration buys a poll the runtime
     * paces and content in an inbox nobody is obliged to read. That is why its
     * provenance can widen later to the server's own `initialize` result, where
     * a hook declaration's cannot.
     *
     * See `src/notifications/types.ts`.
     */
    notifications?: NotificationsDeclaration;
}
/** Briefing declaration — how this app contributes to the daily briefing. */
export interface BriefingBlock {
    priority?: "high" | "medium" | "low";
    facets: BriefingFacet[];
}
/** A single briefing facet — one dimension of summary data.
 *  Resolved via one of: resource (MCP resource read) or tool (MCP tool call).
 *  Both answers come from the server that declared the facet, over MCP. */
export interface BriefingFacet {
    name: string;
    label: string;
    type: "attention" | "upcoming" | "activity" | "delta" | "kpi";
    resource?: string;
    tool?: string;
    tool_input?: Record<string, unknown>;
    /** Shown when the facet declares neither `tool` nor `resource`, and when
     *  resolution fails. The only facet field besides label/type the briefing
     *  reads — see `buildUserPayload` in `services/briefing-generator.ts`. */
    description?: string;
}
/** Runtime tracking for an installed bundle. One per source. */
export interface BundleInstance {
    /** Short server name (e.g. "ipinfo"). Used as the ToolRegistry source key. */
    serverName: string;
    /** Scoped manifest name (e.g. "@nimblebraininc/ipinfo"). Used for identity/display. */
    bundleName: string;
    /** The config key used to find this bundle in nimblebrain.json (the url value). */
    configKey?: string;
    /** Version from manifest. */
    version: string;
    /** Human-readable description from the manifest. */
    description?: string;
    /** Current lifecycle state. */
    state: BundleState;
    /** UI placement metadata from _meta["ai.nimblebrain/host"]. */
    ui: BundleUiMeta | null;
    /** Briefing metadata from _meta["ai.nimblebrain/host"].briefing. */
    briefing: BriefingBlock | null;
    /**
     * Workspace that owns this instance. Required — every bundle instance
     * belongs to exactly one workspace. Global/platform sources are
     * in-process MCP servers (`defineInProcessApp`), not BundleInstance,
     * so they never reach this type.
     */
    wsId: string;
    /**
     * OAuth identity scope for URL bundles. `"workspace"` is the only legal
     * value — one shared identity per `(workspace, server)`. Personal
     * connectors are workspace-scoped to the user's personal workspace
     * (`personalWorkspaceIdFor(userId)`).
     */
    oauthScope?: "workspace";
    /**
     * Per-principal Connections. Each entry is one (bundle, principal)
     * tuple owning an McpSource and its OAuth state machine. For
     * workspace-scoped bundles this map has exactly one entry keyed
     * `WORKSPACE_PRINCIPAL_ID` ("_workspace"); for member-scoped (Step 3)
     * it lazily grows with one entry per active member.
     *
     * `state` above is a derived summary of these — see
     * `summarizeConnectionState` in `connection.ts` and the rules
     * documented there. Updated by lifecycle on every connection transition.
     */
    connections?: Map<string, Connection>;
    /**
     * Original `BundleRef`, retained on the instance so lifecycle can
     * reconstruct sources on-demand. Carries the URL, transport config,
     * oauthClient and scopes.
     */
    ref?: BundleRef;
}
/** Metadata extracted from a local bundle's manifest during startup. */
export interface LocalBundleMeta {
    /** Scoped manifest name (e.g., "@nimblebraininc/hello"). */
    manifestName?: string;
    version: string;
    /** Human-readable description from manifest. */
    description?: string;
    ui: BundleUiMeta | null;
    briefing: BriefingBlock | null;
}
/** Result from starting a bundle source — includes the actual registered source name. */
export interface StartBundleResult {
    meta: LocalBundleMeta | null;
    /** The actual source name registered in the ToolRegistry. */
    sourceName: string;
}
/** App info returned by GET /v1/apps. */
export interface AppInfo {
    name: string;
    bundleName: string;
    version: string;
    status: BundleState;
    toolCount: number;
    ui: BundleUiMeta | null;
}
