/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/connectors/runtime/connection.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
/**
 * Special principal id meaning "the workspace itself" — used when a connector
 * is `oauthScope: "workspace"` (the only mode in Step 1). Member-scoped
 * connectors use the actual member id as the principal.
 *
 * Picked with a leading underscore so it can never collide with a real
 * user id. The underscore-prefix convention is enforced where principal
 * ids are derived from user input.
 */
export declare const WORKSPACE_PRINCIPAL_ID = "_workspace";
/**
 * State machine for a single Connection. A Connection is one
 * (connector, principal) tuple — the operational unit that owns an MCP
 * Client + Transport + auth provider.
 *
 * Transitions:
 *   (init)              → not_authenticated   (URL connector installed, no tokens)
 *   (init)              → starting            (URL connector has persisted tokens; attempting boot)
 *   (init)              → dead                (URL connector installed; boot-start attempted and failed)
 *   (init)              → reauth_required     (boot hit interactive OAuth; the URL was buffered)
 *   not_authenticated   → pending_auth        (user clicked Connect; OAuth flow in progress)
 *   reauth_required     → pending_auth        (user clicked Reconnect after RT failure)
 *   pending_auth        → running             (callback succeeded; tokens stored)
 *   pending_auth        → dead                (callback failed or 15s timeout)
 *   starting            → running             (boot succeeded with persisted tokens)
 *   starting            → reauth_required     (boot failed; refresh token rejected)
 *   starting            → dead                (other transport / network failure)
 *   running             → reauth_required     (refresh failed mid-session)
 *   running             → crashed             (transport error; HealthMonitor may recover)
 *   running             → not_authenticated   (user clicked Disconnect)
 *   crashed             → running             (HealthMonitor recovered)
 *   crashed             → dead                (give up after retries)
 *   *                   → stopped             (explicit uninstall — connector removed)
 *
 * UI contract:
 *   - `not_authenticated`: silent. Connections card shows "Connect" button.
 *   - `pending_auth`: silent during normal flow (browser is being redirected). If we render anything, "Connecting…" + spinner.
 *   - `running`: green pill, "Disconnect" button.
 *   - `reauth_required`: amber pill "Reconnection needed", "Reconnect" button.
 *   - `dead`: red pill "Failed", "Reconnect" button.
 *   - `starting` / `crashed` / `stopped`: transient or end states; surfaced as needed.
 *
 * No global banner — surface state on the Connections page card and inline
 * in chat when a tool call hits an unauthenticated connector.
 */
export type ConnectionState = "starting" | "running" | "crashed" | "dead" | "stopped"
/**
 * URL connector is installed but no tokens exist for this principal. Initial
 * state for a freshly-installed URL connector, and the resting state after
 * `disconnect`. UI shows "Connect" — clicking initiates the OAuth flow
 * (transitioning to `pending_auth`).
 */
 | "not_authenticated"
/**
 * URL connector is actively in an OAuth flow. The user (or agent) clicked
 * Connect; we've captured an authorization URL and are awaiting the
 * browser callback. Tools are unavailable until the callback completes
 * (transitions to `running`) or fails (transitions to `dead`).
 */
 | "pending_auth"
/**
 * URL connector was previously `running` but its refresh token failed (rotated,
 * revoked, or AS rejected). Tools that need this connection will fail until
 * the user reconnects. UI shows "Reconnect" — clicking initiates a fresh
 * OAuth flow (transitioning to `pending_auth`).
 *
 * Distinct from `not_authenticated` so the UI can surface a stronger
 * affordance ("your previously-working connection broke") and from
 * `dead` so the UI knows reconnection is the recovery path.
 */
 | "reauth_required";
/**
 * Operational state for one (connector, principal) tuple.
 *
 * The Connection is the unit that transitions through OAuth states
 * (starting → pending_auth → running). The ConnectorInstance.state is a
 * summary derived from the connection map — for workspace-scoped connectors
 * (only mode in Step 1) it equals the single Connection's state.
 *
 * **A Connection records state; it does not hold the handle.** The McpSource
 * lives in the workspace's `ToolRegistry`, addressed by the same
 * `(wsId, serverName)` this record is already keyed on, and a consumer that
 * needs it asks `ConnectorLifecycleManager.connectionSource`. Holding a second
 * reference here would be a copy governed by nothing: a source is replaced
 * wholesale on every reconnect (`adoptSource` swaps the registry entry and
 * stops the predecessor), and every path that records a state would have to
 * remember to re-record the pointer too.
 *
 * So `running` means one thing: this principal's credential is good and its
 * source is registered. Whether the transport is up this instant is a separate
 * question, and the registry answers it.
 */
export interface Connection {
    /** Principal id this Connection authenticates as. WORKSPACE_PRINCIPAL_ID for workspace-scope. */
    principalId: string;
    /** Current state. Updated by lifecycle, never directly by the McpSource. */
    state: ConnectionState;
    /**
     * Authorization URL to send the user's browser to. Populated only while
     * `state === "pending_auth"`. Read by `/v1/mcp-auth/initiate` to issue
     * the redirect; cleared when the connection transitions away from
     * pending_auth.
     */
    authorizationUrl?: string;
    /** Last error that caused a transition to `crashed` / `dead`. Diagnostic only. */
    lastError?: string;
}
/**
 * Compute a `ConnectionState` summary from a connection map. The map has one
 * entry for workspace-scope and N entries for member-scope (one per active
 * member). Summary rules — most-functional state wins:
 *
 *   - Empty map → "stopped" (connector exists but no principals have any state yet)
 *   - Any "running" → "running" (at least one principal can use the connector)
 *   - Else any "pending_auth" → "pending_auth"
 *   - Else any "starting" → "starting"
 *   - Else any "reauth_required" → "reauth_required"
 *   - Else any "not_authenticated" → "not_authenticated"
 *   - Else any "crashed" → "crashed"
 *   - Else (all "dead" or "stopped") → first state encountered
 *
 * The "any running wins" rule reflects the user-facing intent: if at
 * least one principal can use this connector, the connector is functional.
 */
export declare function summarizeConnectionState(connections: Map<string, Connection>): ConnectionState;
