/**
 * Persistence layer for automations.
 *
 * - automations.json  → definition + scheduling state (atomic write)
 * - runs/{id}.jsonl   → per-automation run history (append-only, pruned at MAX_RUN_LINES)
 *
 * Data lives under {NB_WORK_DIR}/automations/.
 */

import { randomBytes } from "node:crypto";
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { Automation, AutomationRun, AutomationsFile } from "./types.ts";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MAX_RUN_LINES = 1000;
const AUTOMATIONS_FILE = "automations.json";
const RUNS_DIR = "runs";

// ---------------------------------------------------------------------------
// ID Validation
// ---------------------------------------------------------------------------

/**
 * Automation IDs are kebab-case strings generated by toKebabCase():
 * lowercase alphanumeric segments separated by hyphens.
 * Validated before any path construction to prevent path traversal.
 */
const AUTOMATION_ID_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function validateAutomationId(id: string): void {
  if (!AUTOMATION_ID_RE.test(id)) {
    throw new Error(
      `Invalid automation ID: ${JSON.stringify(id)}. Must be non-empty kebab-case (lowercase alphanumeric and hyphens).`,
    );
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function resolveBaseDir(overrideDir?: string): string {
  if (overrideDir) return overrideDir;
  const workDir = process.env.NB_WORK_DIR ?? join(homedir(), ".nimblebrain");
  return join(workDir, "automations");
}

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function runsDir(baseDir: string): string {
  return join(baseDir, RUNS_DIR);
}

function runFilePath(baseDir: string, automationId: string): string {
  validateAutomationId(automationId);
  return join(runsDir(baseDir), `${automationId}.jsonl`);
}

function automationsFilePath(baseDir: string): string {
  return join(baseDir, AUTOMATIONS_FILE);
}

// ---------------------------------------------------------------------------
// Definitions (automations.json)
// ---------------------------------------------------------------------------

/**
 * Load automation definitions from automations.json.
 * Creates the file with an empty array if missing.
 */
export function loadDefinitions(overrideDir?: string): Map<string, Automation> {
  const baseDir = resolveBaseDir(overrideDir);
  ensureDir(baseDir);
  const filePath = automationsFilePath(baseDir);

  if (!existsSync(filePath)) {
    const empty: AutomationsFile = {
      version: 1,
      updatedAtMs: Date.now(),
      automations: [],
    };
    writeFileSync(filePath, `${JSON.stringify(empty, null, 2)}\n`);
  }

  const content = readFileSync(filePath, "utf-8");
  const data = JSON.parse(content) as AutomationsFile;
  const map = new Map<string, Automation>();
  for (const a of data.automations) {
    map.set(a.id, a);
  }
  return map;
}

/**
 * Save automation definitions atomically (temp file + rename).
 */
export function saveDefinitions(automations: Map<string, Automation>, overrideDir?: string): void {
  const baseDir = resolveBaseDir(overrideDir);
  ensureDir(baseDir);
  const filePath = automationsFilePath(baseDir);
  const tmpPath = `${filePath}.${randomBytes(6).toString("hex")}.tmp`;

  const file: AutomationsFile = {
    version: 1,
    updatedAtMs: Date.now(),
    automations: Array.from(automations.values()),
  };

  writeFileSync(tmpPath, `${JSON.stringify(file, null, 2)}\n`);
  renameSync(tmpPath, filePath);
}

// ---------------------------------------------------------------------------
// Runs (runs/{automationId}.jsonl)
// ---------------------------------------------------------------------------

/**
 * Append a run to the automation's JSONL run file.
 * Creates directories and file if missing.
 * Prunes oldest lines if file exceeds MAX_RUN_LINES.
 */
export function appendRun(automationId: string, run: AutomationRun, overrideDir?: string): void {
  const baseDir = resolveBaseDir(overrideDir);
  const dir = runsDir(baseDir);
  ensureDir(dir);
  const filePath = runFilePath(baseDir, automationId);

  appendFileSync(filePath, `${JSON.stringify(run)}\n`);

  // Prune if over limit
  const content = readFileSync(filePath, "utf-8").trimEnd();
  const lines = content.split("\n");
  if (lines.length > MAX_RUN_LINES) {
    const trimmed = lines.slice(lines.length - MAX_RUN_LINES);
    writeFileSync(filePath, `${trimmed.join("\n")}\n`);
  }
}

/**
 * Update the last line in the run file that matches run.id.
 * Rewrites the file with the updated line.
 */
export function updateRun(automationId: string, run: AutomationRun, overrideDir?: string): void {
  const baseDir = resolveBaseDir(overrideDir);
  const filePath = runFilePath(baseDir, automationId);

  if (!existsSync(filePath)) return;

  const content = readFileSync(filePath, "utf-8").trimEnd();
  if (!content) return;

  const lines = content.split("\n");

  // Find last line matching run.id (search from end)
  for (let i = lines.length - 1; i >= 0; i--) {
    try {
      const parsed = JSON.parse(lines[i]!) as AutomationRun;
      if (parsed.id === run.id) {
        lines[i] = JSON.stringify(run);
        break;
      }
    } catch {
      // skip malformed
    }
  }

  writeFileSync(filePath, `${lines.join("\n")}\n`);
}

// ---------------------------------------------------------------------------
// Read Runs
// ---------------------------------------------------------------------------

export interface ReadRunsOptions {
  limit?: number;
  since?: string; // ISO timestamp
  status?: AutomationRun["status"];
}

/**
 * Read run history for a single automation.
 * Returns newest first, with optional filters.
 */
export function readRuns(
  automationId: string,
  opts?: ReadRunsOptions,
  overrideDir?: string,
): AutomationRun[] {
  const baseDir = resolveBaseDir(overrideDir);
  const filePath = runFilePath(baseDir, automationId);

  if (!existsSync(filePath)) return [];

  const content = readFileSync(filePath, "utf-8").trimEnd();
  if (!content) return [];

  const lines = content.split("\n");
  let runs: AutomationRun[] = [];

  for (const line of lines) {
    try {
      runs.push(JSON.parse(line) as AutomationRun);
    } catch {
      // skip malformed
    }
  }

  // Newest first
  runs.reverse();

  // Apply filters
  runs = applyFilters(runs, opts);

  return runs;
}

/**
 * Read runs across all automation run files.
 * Returns newest first, with optional filters.
 */
export function readAllRuns(opts?: ReadRunsOptions, overrideDir?: string): AutomationRun[] {
  const baseDir = resolveBaseDir(overrideDir);
  const dir = runsDir(baseDir);

  if (!existsSync(dir)) return [];

  let files: string[];
  try {
    files = readdirSync(dir).filter((f) => f.endsWith(".jsonl"));
  } catch {
    return [];
  }

  let allRuns: AutomationRun[] = [];
  for (const file of files) {
    const content = readFileSync(join(dir, file), "utf-8").trimEnd();
    if (!content) continue;
    for (const line of content.split("\n")) {
      try {
        allRuns.push(JSON.parse(line) as AutomationRun);
      } catch {
        // skip malformed
      }
    }
  }

  // Newest first by startedAt
  allRuns.sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime());

  allRuns = applyFilters(allRuns, opts);

  return allRuns;
}

function applyFilters(runs: AutomationRun[], opts?: ReadRunsOptions): AutomationRun[] {
  let result = runs;

  if (opts?.since) {
    const sinceMs = new Date(opts.since).getTime();
    result = result.filter((r) => new Date(r.startedAt).getTime() >= sinceMs);
  }

  if (opts?.status) {
    result = result.filter((r) => r.status === opts.status);
  }

  if (opts?.limit !== undefined) {
    result = result.slice(0, opts.limit);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Orphan Detection
// ---------------------------------------------------------------------------

/**
 * Scan all run files for runs with status "running" and no completedAt.
 * Marks them as "failure" with an error message.
 * Returns the number of orphans found and fixed.
 */
export function detectOrphans(overrideDir?: string): number {
  const baseDir = resolveBaseDir(overrideDir);
  const dir = runsDir(baseDir);

  if (!existsSync(dir)) return 0;

  let files: string[];
  try {
    files = readdirSync(dir).filter((f) => f.endsWith(".jsonl"));
  } catch {
    return 0;
  }

  let orphanCount = 0;

  for (const file of files) {
    const filePath = join(dir, file);
    const content = readFileSync(filePath, "utf-8").trimEnd();
    if (!content) continue;

    const lines = content.split("\n");
    let modified = false;

    for (let i = 0; i < lines.length; i++) {
      try {
        const run = JSON.parse(lines[i]!) as AutomationRun;
        if (run.status === "running" && !run.completedAt) {
          const updated: AutomationRun = {
            ...run,
            status: "failure",
            completedAt: new Date().toISOString(),
            error: "Orphaned run detected on startup (process exited while running)",
          };
          lines[i] = JSON.stringify(updated);
          modified = true;
          orphanCount++;
        }
      } catch {
        // skip malformed
      }
    }

    if (modified) {
      writeFileSync(filePath, `${lines.join("\n")}\n`);
    }
  }

  return orphanCount;
}
