#!/usr/bin/env bun
/**
 * Generates `web/src/_generated/platform-schemas/` from the canonical
 * TypeBox schemas at `src/tools/platform/schemas/`.
 *
 * Why this exists: web is a separate package (its own Dockerfile,
 * package.json, build context). The web shell needs the catalog's
 * derived TYPES — `ToolInput<S, T>`, `ToolSource`, `ToolName<S>` — for
 * the typed `callTool<S, T>(args)` API in `web/src/api/client.ts` and
 * the `CreateInput` alias in `web/src/pages/settings/SkillsTab.tsx`.
 * It does NOT need the runtime schemas (TypeBox values).
 *
 * Sharing this via a cross-tree TypeScript path alias would force every
 * Dockerfile, dockerignore, Makefile, docker-compose, and CI invocation
 * to know about the cross-tree relationship. Generating a flat .d.ts
 * tree inside web/ keeps web a self-contained package — its build
 * doesn't reach outside web/, and the generated artifact is a normal
 * source file in version control.
 *
 * The generated tree is checked in. CI runs this script and verifies
 * `git diff --exit-code web/src/_generated/` to catch drift.
 *
 * Run: `bun run codegen` (alias for this script — see package.json).
 */

import { execSync } from "node:child_process";
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname ?? __dirname, "..");
const SCHEMA_SRC = join(REPO_ROOT, "src/tools/platform/schemas");
const TMP_OUT = join(REPO_ROOT, ".tmp-codegen");
const WEB_DEST = join(REPO_ROOT, "web/src/_generated/platform-schemas");

/**
 * Per-file header injected at the top of every generated .d.ts.
 * No timestamp — would change every regen and defeat the CI drift
 * check (`git log <file>` is the authoritative regen record).
 */
function header(sourcePath: string): string {
  return `/**
 * AUTOGENERATED — DO NOT EDIT. Source: ${sourcePath}
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
`;
}

/** Recursively prepend the header to every .d.ts file in `dir`. */
function injectHeaders(dir: string, sourceRoot: string): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      injectHeaders(full, sourceRoot);
      continue;
    }
    if (!entry.name.endsWith(".d.ts")) continue;
    // Map output path back to source path for the header.
    const relFromOutput = full.slice(WEB_DEST.length + 1).replace(/\.d\.ts$/, ".ts");
    const sourcePath = `src/tools/platform/schemas/${relFromOutput}`;
    const body = readFileSync(full, "utf-8");
    writeFileSync(full, header(sourcePath) + body);
  }
}

console.log("[codegen] platform-schemas → web/src/_generated/platform-schemas/");

// Clean previous outputs so removed schemas don't leave stale .d.ts files.
rmSync(TMP_OUT, { recursive: true, force: true });
rmSync(WEB_DEST, { recursive: true, force: true });

// Emit declarations only via the dedicated tsconfig. The dedicated config
// keeps the generation independent of the project tsconfig (which uses
// `noEmit` and other compile-time-only settings).
execSync(`bunx tsc -p scripts/tsconfig.codegen-web.json`, {
  cwd: REPO_ROOT,
  stdio: "inherit",
});

// The tsc output preserves the source dir structure under `outDir`.
// Move just the schemas tree into web/src/_generated/.
mkdirSync(dirname(WEB_DEST), { recursive: true });
cpSync(TMP_OUT, WEB_DEST, { recursive: true });
rmSync(TMP_OUT, { recursive: true, force: true });

// Inject the do-not-edit header into every generated file.
injectHeaders(WEB_DEST, SCHEMA_SRC);

console.log(`[codegen] OK → ${WEB_DEST.replace(REPO_ROOT, ".")}`);
