#!/usr/bin/env bun
/**
 * Generates the `.d.ts` trees under `web/src/_generated/` from the server-side
 * sources that own their shapes: the TypeBox schemas at
 * `src/tools/platform/schemas/`, and the connector-registry wire types at
 * `src/registries/types.ts`.
 *
 * Why this exists: web is a separate package (its own Dockerfile,
 * package.json, build context). The web shell needs the catalog's
 * derived TYPES — `ToolInput<S, T>`, `ToolSource`, `ToolName<S>` — for
 * the typed `callTool<S, T>(args)` API in `web/src/api/client.ts` and
 * the `CreateInput` alias in `web/src/pages/settings/SkillsTab.tsx`.
 * It does NOT need the runtime schemas (TypeBox values).
 *
 * Sharing this via a cross-tree TypeScript path alias would force every
 * Dockerfile, dockerignore, Makefile, docker-compose, and CI invocation
 * to know about the cross-tree relationship. Generating a flat .d.ts
 * tree inside web/ keeps web a self-contained package — its build
 * doesn't reach outside web/, and the generated artifact is a normal
 * source file in version control.
 *
 * The generated trees are checked in. `scripts/check-codegen.ts` runs
 * after this script and fails on anything git reports under
 * `web/src/_generated/` — including a file this generator emitted that
 * was never added to git, which a diff over tracked paths cannot see.
 * That is what stops a client-side copy of a server type from drifting:
 * add a field to `RemoteOAuthInstall` without regenerating and CI fails,
 * rather than the field being quietly invisible to the web shell.
 *
 * Run: `bun run codegen` (alias for this script — see package.json).
 */

import { execSync } from "node:child_process";
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname ?? __dirname, "..");
const TMP_OUT = join(REPO_ROOT, ".tmp-codegen");
const WEB_DEST = join(REPO_ROOT, "web/src/_generated/platform-schemas");
const WORKSPACE_ID_PATTERN_SRC = join(REPO_ROOT, "src/workspace/workspace-id-pattern.ts");
const WORKSPACE_ID_PATTERN_DEST = join(REPO_ROOT, "web/src/_generated/workspace-id-pattern.ts");
const CONNECTOR_TYPES_TMP = join(REPO_ROOT, ".tmp-codegen-connectors");
const CONNECTOR_TYPES_DEST = join(REPO_ROOT, "web/src/_generated/connector-registry");
const IDENTITY_SOURCES_SRC = join(REPO_ROOT, "src/tools/identity-sources.ts");
const PERSONAL_CONNECTOR_PREFIX_DEST = join(
  REPO_ROOT,
  "web/src/_generated/personal-connector-prefix.ts",
);

/**
 * Per-file header injected at the top of every generated .d.ts.
 * No timestamp — would change every regen and defeat the CI drift
 * check (`git log <file>` is the authoritative regen record).
 */
function header(sourcePath: string): string {
  return `/**
 * AUTOGENERATED — DO NOT EDIT. Source: ${sourcePath}
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
`;
}

/**
 * Recursively prepend the header to every .d.ts under `dir`, naming the source
 * each file came from. `treeRoot` is the emitted tree's own root and `sourceRoot`
 * the repo-relative directory its layout mirrors, so the path a reader is sent to
 * is the real one for whichever tree this is called on.
 */
function injectHeaders(dir: string, treeRoot: string, sourceRoot: string): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      injectHeaders(full, treeRoot, sourceRoot);
      continue;
    }
    if (!entry.name.endsWith(".d.ts")) continue;
    // Map output path back to source path for the header.
    const relFromOutput = full.slice(treeRoot.length + 1).replace(/\.d\.ts$/, ".ts");
    const body = readFileSync(full, "utf-8");
    writeFileSync(full, header(`${sourceRoot}/${relFromOutput}`) + body);
  }
}

// ── workspace-id-pattern (Stage 2 / T012) ──────────────────────────
//
// Emits a runtime `.ts` mirroring the literal pattern + flags exported
// from `src/workspace/workspace-id-pattern.ts`. The web tier
// (`web/src/lib/namespaced-tool.ts`) imports the generated copy and
// constructs its own RegExp locally. CI's `check:codegen` step
// catches drift between the server source and the emitted copy.
//
// Why we don't ship a `.d.ts` here: the web tier needs the actual
// string values at runtime to validate workspace ids. `.d.ts` would
// only give us type-level types. So this step is a hand-written extract
// of the two string literals — no `tsc` emission needed.

function extractStringLiteral(source: string, name: string): string {
  // Match `export const <name> = "<value>";` with the value as a
  // double-quoted JS string literal. No escapes are interpreted — the
  // workspace-id pattern uses only ASCII + the chars `^$_{},|[]0-9a-z`,
  // none of which need escaping in a JS string. If a future change to
  // the source adds escapes, this regex needs to widen accordingly.
  const re = new RegExp(`export\\s+const\\s+${name}\\s*=\\s*"([^"\\\\]*)"`);
  const m = re.exec(source);
  if (!m || typeof m[1] !== "string") {
    throw new Error(
      `[codegen] could not extract ${name} — the source file format may have changed`,
    );
  }
  return m[1];
}

console.log("[codegen] workspace-id-pattern → web/src/_generated/workspace-id-pattern.ts");

{
  const src = readFileSync(WORKSPACE_ID_PATTERN_SRC, "utf-8");
  const pattern = extractStringLiteral(src, "WORKSPACE_ID_PATTERN");
  const flags = extractStringLiteral(src, "WORKSPACE_ID_FLAGS");

  // JSON.stringify produces a safely-quoted JS string literal even if
  // someone slips a `"` or `\` into the pattern later. Defense in depth
  // against silent codegen breakage.
  const patternLiteral = JSON.stringify(pattern);
  const flagsLiteral = JSON.stringify(flags);

  const body = `${header("src/workspace/workspace-id-pattern.ts")}
// Workspace-id pattern + flags mirrored from the server-side source.
// The web tier rebuilds the regex locally; see the source file's
// header for the contract.

export const WORKSPACE_ID_PATTERN = ${patternLiteral};
export const WORKSPACE_ID_FLAGS = ${flagsLiteral};
`;

  mkdirSync(dirname(WORKSPACE_ID_PATTERN_DEST), { recursive: true });
  writeFileSync(WORKSPACE_ID_PATTERN_DEST, body);
  console.log(`[codegen] OK → ${WORKSPACE_ID_PATTERN_DEST.replace(REPO_ROOT, ".")}`);
}

console.log(
  "[codegen] personal-connector-prefix → web/src/_generated/personal-connector-prefix.ts",
);

{
  // Mirrored for the same reason as the workspace-id pattern, and with more at
  // stake: this marker is what separates the caller's own connector from a
  // same-named workspace source. A hand-copied copy that drifts stops the web
  // tier recognising a marked name, which mounts a workspace app's iframe for a
  // connector's tool call — the exact collision the marker exists to prevent,
  // and nothing else would catch it. `check:codegen` turns drift into a build
  // failure instead of a comment asking for discipline.
  const src = readFileSync(IDENTITY_SOURCES_SRC, "utf-8");
  const prefix = extractStringLiteral(src, "PERSONAL_CONNECTOR_PREFIX");

  const body = `${header("src/tools/identity-sources.ts")}
// Personal-connector wire marker, mirrored from the server-side source.
// See that file's header for why the marker sits outside slugify's alphabet.

export const PERSONAL_CONNECTOR_PREFIX = ${JSON.stringify(prefix)};
`;

  mkdirSync(dirname(PERSONAL_CONNECTOR_PREFIX_DEST), { recursive: true });
  writeFileSync(PERSONAL_CONNECTOR_PREFIX_DEST, body);
  console.log(`[codegen] OK → ${PERSONAL_CONNECTOR_PREFIX_DEST.replace(REPO_ROOT, ".")}`);
}

console.log("[codegen] platform-schemas → web/src/_generated/platform-schemas/");

// Clean previous outputs so removed schemas don't leave stale .d.ts files.
rmSync(TMP_OUT, { recursive: true, force: true });
rmSync(WEB_DEST, { recursive: true, force: true });

// Emit declarations only via the dedicated tsconfig. The dedicated config
// keeps the generation independent of the project tsconfig (which uses
// `noEmit` and other compile-time-only settings).
execSync(`bunx tsc -p scripts/tsconfig.codegen-web.json`, {
  cwd: REPO_ROOT,
  stdio: "inherit",
});

// The tsc output preserves the source dir structure under `outDir`.
// Move just the schemas tree into web/src/_generated/.
mkdirSync(dirname(WEB_DEST), { recursive: true });
cpSync(TMP_OUT, WEB_DEST, { recursive: true });
rmSync(TMP_OUT, { recursive: true, force: true });

// Inject the do-not-edit header into every generated file.
injectHeaders(WEB_DEST, WEB_DEST, "src/tools/platform/schemas");

console.log(`[codegen] OK → ${WEB_DEST.replace(REPO_ROOT, ".")}`);

// ── connector-registry wire types ──────────────────────────────────
//
// `web/src/api/client.ts` used to re-declare `DirectoryEntry` /
// `ConnectorCatalogEntry` by hand, and the copy drifted: `providerAuth` and
// `secretHeaders` were on the wire and absent from the client, which made a
// whole credential class invisible to the UI with nothing to notice. The web
// shell now imports these, and `check:codegen` fails the build when the server
// type moves without a regen.
//
// Only the type closure of `src/registries/types.ts` is emitted — a small set
// of leaf type modules. `ConnectorCatalogEntry` lives there beside
// `DirectoryEntry` for that reason: the projection module that builds it also
// imports half the runtime, and rooting the emit at a module with runtime
// imports pulls ~80 files into a tree the web shell has no use for.

console.log("[codegen] connector-registry → web/src/_generated/connector-registry/");

rmSync(CONNECTOR_TYPES_TMP, { recursive: true, force: true });
rmSync(CONNECTOR_TYPES_DEST, { recursive: true, force: true });

execSync(`bunx tsc -p scripts/tsconfig.codegen-web-connectors.json`, {
  cwd: REPO_ROOT,
  stdio: "inherit",
});

mkdirSync(dirname(CONNECTOR_TYPES_DEST), { recursive: true });
cpSync(CONNECTOR_TYPES_TMP, CONNECTOR_TYPES_DEST, { recursive: true });
rmSync(CONNECTOR_TYPES_TMP, { recursive: true, force: true });

injectHeaders(CONNECTOR_TYPES_DEST, CONNECTOR_TYPES_DEST, "src");

console.log(`[codegen] OK → ${CONNECTOR_TYPES_DEST.replace(REPO_ROOT, ".")}`);
