/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/notifications.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
/**
 * Canonical urgency vocabulary, ordered least to most urgent. Single source of
 * truth: the TypeBox enum below, the {@link NotificationLevel} type, and the
 * domain's rank map (`src/notifications/types.ts`) all derive from this array,
 * so a fourth level is added in exactly one place.
 *
 * It lives here rather than in `src/notifications/` for the same reason
 * `USAGE_GROUP_BYS` does: this directory is the one the web codegen compiles,
 * and it must stay self-contained.
 */
export declare const NOTIFICATION_LEVELS: readonly ["info", "attention", "urgent"];
export type NotificationLevel = (typeof NOTIFICATION_LEVELS)[number];
/** Page sizes for every notification list — the tool and the store. */
export declare const NOTIFICATION_LIST_DEFAULT_LIMIT = 20;
export declare const NOTIFICATION_LIST_MAX_LIMIT = 100;
export declare const NotificationsListInput: import("@sinclair/typebox").TObject<{
    unreadOnly: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TBoolean>;
    level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
    source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    after: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    order: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"desc" | "asc">>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
}>;
export type NotificationsListInput = Static<typeof NotificationsListInput>;
export declare const NotificationsMarkReadInput: import("@sinclair/typebox").TObject<{
    ids: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>;
}>;
export type NotificationsMarkReadInput = Static<typeof NotificationsMarkReadInput>;
/**
 * How one route target fared for one notification.
 *
 * The ledger is what makes a failed delivery visible instead of silent: a
 * notification that reached the inbox and never reached the Slack channel it
 * was routed to looks identical to one nobody routed, unless the attempt is
 * recorded. Empty until routes are dispatched.
 *
 * It lives in this directory rather than in `src/notifications/` because it
 * crosses to the web on `NotificationView`, and this is the one directory the
 * web codegen compiles; the domain re-exports it.
 */
export interface DeliveryRecord {
    /** The route that matched, from the workspace record. */
    routeId: string;
    /** What the route aimed at — a tool name, or an automation id. */
    target: string;
    attempts: number;
    lastError?: string;
    outcome: "delivered" | "failed" | "skipped";
}
/**
 * The wire shape of one inbox item — what `notifications__list` returns, and
 * the only projection of a stored record that leaves the runtime.
 *
 * It is a flattening of the stored record, not a subset with a policy in it:
 * the presentation block is resolved with its defaults applied and the
 * envelope's identity fields are lifted beside it.
 *
 * `data` is the emitting server's own structured payload, forwarded verbatim.
 * No runtime code reads a field of it — it crosses this boundary the way a
 * tool result's `structuredContent` does, and carries exactly as much
 * authority: it is data a connector wrote, not an instruction.
 */
export interface NotificationView {
    /** `<source>:<eventId>`. What `notifications__mark_read` is addressed with. */
    id: string;
    /** Monotonic position in this workspace's inbox. */
    seq: number;
    /** The connector that emitted it, stamped by the runtime. */
    source: string;
    /** The server's own event name. */
    name: string;
    level: NotificationLevel;
    title: string;
    subject?: string;
    body?: string;
    link?: {
        resource: string;
    };
    /** When the emitting server says the fact happened. */
    timestamp: string;
    /** When this runtime wrote it. */
    receivedAt: string;
    readAt?: string;
    /**
     * One row per route target that has been tried. Absent while nothing has
     * tried — an empty ledger is not a fact worth rendering, and omitting it
     * keeps every item in a routeless workspace one field smaller.
     */
    deliveries?: DeliveryRecord[];
    data: Record<string, unknown>;
}
export interface NotificationsListOutput {
    notifications: NotificationView[];
    /**
     * Highest `seq` in this page, absent when the page is empty. Pass it back as
     * `after` to continue — forward through a backlog under `order: "asc"`, or
     * as a "what has arrived since" mark under the default newest-first order,
     * which does not walk backwards.
     */
    cursor?: number;
}
export interface NotificationsMarkReadOutput {
    /** Ids that were unread in this workspace and are now read. */
    marked: string[];
    /**
     * Ids that named nothing markable here — unknown, already read, malformed,
     * or belonging to another workspace, which this session cannot reach.
     */
    skipped: string[];
}
/**
 * Level a newly declared source is held to until an admin raises it.
 *
 * Declaring an outbox grants nothing on its own: a connector can put items in
 * the inbox by declaring one, but a route above this ceiling does not fire for
 * it until a workspace admin says so. `info` is the floor of the
 * vocabulary, so the default is "nothing this source emits reaches a route that
 * asks for urgency".
 */
export declare const DEFAULT_SOURCE_MAX_LEVEL: NotificationLevel;
/**
 * The only placeholders a `kind: "tool"` input may carry.
 *
 * Resolved from the notification's presentation block — which is why `data` is
 * absent: the runtime does not read a connector's payload, so it cannot
 * template out of one. Mustache-style, no logic. A route naming anything else
 * is rejected at write time rather than rendering the literal braces into
 * somebody's Slack channel.
 */
export declare const NOTIFICATION_PLACEHOLDERS: readonly ["title", "body", "subject", "link.resource"];
export type NotificationPlaceholder = (typeof NOTIFICATION_PLACEHOLDERS)[number];
export declare const NotificationRouteMatch: import("@sinclair/typebox").TObject<{
    source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
}>;
export type NotificationRouteMatch = Static<typeof NotificationRouteMatch>;
export declare const NotificationDeliverTarget: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
    kind: import("@sinclair/typebox").TLiteral<"tool">;
    tool: import("@sinclair/typebox").TString;
    input: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
}>, import("@sinclair/typebox").TObject<{
    kind: import("@sinclair/typebox").TLiteral<"agent">;
    automation: import("@sinclair/typebox").TString;
}>]>;
export type NotificationDeliverTarget = Static<typeof NotificationDeliverTarget>;
/** Most targets one route may fan out to. */
export declare const NOTIFICATION_ROUTE_MAX_DELIVER = 5;
/** Most routes one workspace may hold. */
export declare const NOTIFICATION_ROUTES_MAX = 50;
/**
 * Most sources one workspace may hold a ceiling for.
 *
 * The map lives on the workspace record, and the inbound-delivery door reads
 * every workspace record in full on every delivery — a walk that stays cheap
 * only because those records stay small. A ceiling is one entry per connector
 * that ever declared an outbox, so this bound is far above any real workspace
 * and exists to keep an unbounded key space off that path.
 */
export declare const NOTIFICATION_SOURCES_MAX = 200;
/**
 * One route as the editor writes it.
 *
 * `createdBy` is absent by construction, not filtered: the schema is closed, so
 * a body carrying it — or an `as`, or any other principal-shaped field — is
 * refused by the validator before the handler runs. The principal a route
 * dispatches under is stamped from the authenticated identity, and a field the
 * caller could set would be the impersonation this design forbids.
 */
export declare const NotificationRouteInput: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    match: import("@sinclair/typebox").TObject<{
        source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
    }>;
    deliver: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
        kind: import("@sinclair/typebox").TLiteral<"tool">;
        tool: import("@sinclair/typebox").TString;
        input: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
    }>, import("@sinclair/typebox").TObject<{
        kind: import("@sinclair/typebox").TLiteral<"agent">;
        automation: import("@sinclair/typebox").TString;
    }>]>>;
}>;
export type NotificationRouteInput = Static<typeof NotificationRouteInput>;
export declare const NotificationsSetRoutesInput: import("@sinclair/typebox").TObject<{
    routes: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        match: import("@sinclair/typebox").TObject<{
            source: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            level: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">>;
        }>;
        deliver: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TObject<{
            kind: import("@sinclair/typebox").TLiteral<"tool">;
            tool: import("@sinclair/typebox").TString;
            input: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnsafe<Record<string, unknown>>>;
        }>, import("@sinclair/typebox").TObject<{
            kind: import("@sinclair/typebox").TLiteral<"agent">;
            automation: import("@sinclair/typebox").TString;
        }>]>>;
    }>>;
}>;
export type NotificationsSetRoutesInput = Static<typeof NotificationsSetRoutesInput>;
export declare const NotificationsSetSourceLevelInput: import("@sinclair/typebox").TObject<{
    source: import("@sinclair/typebox").TString;
    maxLevel: import("@sinclair/typebox").TUnsafe<"info" | "attention" | "urgent">;
}>;
export type NotificationsSetSourceLevelInput = Static<typeof NotificationsSetSourceLevelInput>;
export declare const NotificationsSettingsInput: import("@sinclair/typebox").TObject<{}>;
export type NotificationsSettingsInput = Static<typeof NotificationsSettingsInput>;
/** One connector that declares an outbox, and the ceiling it is held to. */
export interface NotificationSourceView {
    /** The connector's server name — what the runtime stamps on an item's `source`. */
    source: string;
    /** Display name from the catalog, falling back to the server name. */
    label: string;
    /** What the connector says its outbox carries. Operator-facing prose. */
    description?: string;
    /** The effective ceiling: what an admin set, or {@link DEFAULT_SOURCE_MAX_LEVEL}. */
    maxLevel: NotificationLevel;
    /** False while the source is still at the default — nobody has raised it. */
    configured: boolean;
}
/** One stored route, with the principal it dispatches under. */
export interface NotificationRouteView {
    id: string;
    /** The admin who last wrote this route. Stamped server-side; never sent. */
    createdBy: string;
    match: NotificationRouteMatch;
    deliver: NotificationDeliverTarget[];
}
/**
 * Everything the workspace settings surface needs to render and validate the
 * notifications configuration, in one read.
 *
 * The pickers and the validator are fed from the same call deliberately: a
 * route the editor could offer but the handler would refuse is the drift this
 * shape exists to prevent.
 */
export interface NotificationsSettingsOutput {
    sources: NotificationSourceView[];
    routes: NotificationRouteView[];
    /** Tool names a `kind: "tool"` target may name — this workspace's installed set. */
    deliverableTools: string[];
    /** Automations the caller owns in this workspace, for a `kind: "agent"` target. */
    automations: {
        id: string;
        name: string;
    }[];
    /** The placeholders a tool input may carry. */
    placeholders: readonly string[];
    /**
     * Whether a matching route actually runs. False while the dispatch half is
     * unbuilt: routes are stored, validated and shown, and nothing reads them.
     * The editor says so rather than implying a delivery that will not happen.
     */
    routesExecuted: boolean;
}
