/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/identity-sources.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */

// Personal-connector wire marker, mirrored from the server-side source.
// See that file's header for why the marker sits outside slugify's alphabet.

export const PERSONAL_CONNECTOR_PREFIX = "my_";
